"""Diagnostic harness for *Deep Learning: Making It Trainable*."""

from .precision import (
    QuantizationResult,
    UpdateTrace,
    float_contract,
    local_spacing,
    repeated_update,
    stochastic_update_trials,
    symmetric_quantize,
)
from .optimization import (
    NoisyQuadraticSummary,
    QuadraticTrace,
    classify_mode_factors,
    quadratic_spectrum,
    quadratic_trace,
    scalar_noisy_quadratic_trials,
)
from .geometry import (
    circle_covering_radius,
    circle_epsilon_net,
    operator_net_certificate,
    operator_net_estimate,
    sphere_cover_log_upper,
    uniform_subgaussian_threshold,
)
from .spectra import (
    EffectiveRankSummary,
    MarchenkoPasturSupport,
    PowerIterationResult,
    SpectrumSummary,
    covariance_eigenvalues,
    effective_rank_psd,
    empirical_upper_threshold,
    gaussian_covariance_trials,
    gaussian_covariance_error_trials,
    gaussian_singular_value_trials,
    marchenko_pastur_density,
    marchenko_pastur_support,
    matrix_spectrum_summary,
    power_iteration_spectral_norm,
    sample_covariance,
    stable_rank,
)
from .autodiff import (
    CheckpointCost,
    TapeNode,
    reverse_accumulate,
    uniform_checkpoint_cost,
)
from .curvature import (
    CurvatureMatrices,
    EigenpairEstimate,
    bernoulli_curvature_matrices,
    bernoulli_hessian_vector_product,
    dominant_symmetric_eigenpair,
)
from .probability import (
    bernstein_two_regime_rate,
    centered_chi_square_log_mgf,
    centered_chi_square_sum_trials,
    centered_chi_square_sum_upper_tail,
    centered_chi_square_upper_tail,
    centered_pareto_clip_bias,
    empirical_tail_profile,
    moment_growth_profile,
    rademacher_projection_trials,
    standard_normal_maxima,
    subgaussian_max_threshold,
)
from .streaming import (
    MomentState,
    comparison_audit,
    merge_moments,
    naive_moments,
    observation_ledger,
    stable_online_moments,
)
from .stochastic import (
    QuadraticRegime,
    conditional_safe_step,
    scalar_quadratic_regime,
    two_point_clipping_audit,
)
from .criticality import (
    deep_linear_product,
    mean_squared_singular_value,
    relu_correlation_trace,
    relu_moment_fluctuation_variance,
    relu_variance_trace,
)
from .normalization import (
    centered_normalize,
    normalization_jacobian,
    raw_and_centered_variance,
    rms_normalize,
)
from .stability import (
    StabilityTrace,
    moving_curvature_trace,
    valley_loss_gradient_hessian,
)
from .update_geometry import (
    newton_schulz_polar,
    norm_steepest_directions,
    polar_factor,
)

__all__ = [
    "MomentState",
    "CheckpointCost",
    "CurvatureMatrices",
    "EffectiveRankSummary",
    "EigenpairEstimate",
    "MarchenkoPasturSupport",
    "NoisyQuadraticSummary",
    "PowerIterationResult",
    "QuantizationResult",
    "QuadraticTrace",
    "QuadraticRegime",
    "SpectrumSummary",
    "StabilityTrace",
    "TapeNode",
    "UpdateTrace",
    "bernstein_two_regime_rate",
    "bernoulli_curvature_matrices",
    "bernoulli_hessian_vector_product",
    "centered_chi_square_log_mgf",
    "centered_chi_square_sum_trials",
    "centered_chi_square_sum_upper_tail",
    "centered_chi_square_upper_tail",
    "centered_normalize",
    "centered_pareto_clip_bias",
    "circle_covering_radius",
    "circle_epsilon_net",
    "comparison_audit",
    "conditional_safe_step",
    "covariance_eigenvalues",
    "classify_mode_factors",
    "empirical_tail_profile",
    "empirical_upper_threshold",
    "effective_rank_psd",
    "dominant_symmetric_eigenpair",
    "deep_linear_product",
    "float_contract",
    "gaussian_covariance_trials",
    "gaussian_covariance_error_trials",
    "gaussian_singular_value_trials",
    "local_spacing",
    "merge_moments",
    "marchenko_pastur_density",
    "marchenko_pastur_support",
    "matrix_spectrum_summary",
    "moment_growth_profile",
    "moving_curvature_trace",
    "mean_squared_singular_value",
    "naive_moments",
    "newton_schulz_polar",
    "norm_steepest_directions",
    "normalization_jacobian",
    "observation_ledger",
    "operator_net_certificate",
    "operator_net_estimate",
    "polar_factor",
    "power_iteration_spectral_norm",
    "quadratic_spectrum",
    "quadratic_trace",
    "rademacher_projection_trials",
    "raw_and_centered_variance",
    "repeated_update",
    "relu_correlation_trace",
    "relu_moment_fluctuation_variance",
    "relu_variance_trace",
    "reverse_accumulate",
    "rms_normalize",
    "stable_online_moments",
    "scalar_noisy_quadratic_trials",
    "scalar_quadratic_regime",
    "sample_covariance",
    "stable_rank",
    "sphere_cover_log_upper",
    "standard_normal_maxima",
    "stochastic_update_trials",
    "symmetric_quantize",
    "uniform_subgaussian_threshold",
    "uniform_checkpoint_cost",
    "valley_loss_gradient_hessian",
    "subgaussian_max_threshold",
    "two_point_clipping_audit",
]

__version__ = "0.18.0"
