"""Diagnostic harness for *Deep Learning: Making It Trainable*."""

from .precision import (
    QuantizationResult,
    UpdateTrace,
    float_contract,
    local_spacing,
    repeated_update,
    stochastic_update_trials,
    symmetric_quantize,
)
from .optimization import (
    NoisyQuadraticSummary,
    QuadraticTrace,
    classify_mode_factors,
    quadratic_spectrum,
    quadratic_trace,
    scalar_noisy_quadratic_trials,
)
from .geometry import (
    circle_covering_radius,
    circle_epsilon_net,
    operator_net_certificate,
    operator_net_estimate,
    sphere_cover_log_upper,
    uniform_subgaussian_threshold,
)
from .spectra import (
    MarchenkoPasturSupport,
    PowerIterationResult,
    SpectrumSummary,
    covariance_eigenvalues,
    empirical_upper_threshold,
    gaussian_covariance_trials,
    gaussian_singular_value_trials,
    marchenko_pastur_density,
    marchenko_pastur_support,
    matrix_spectrum_summary,
    power_iteration_spectral_norm,
    sample_covariance,
)
from .probability import (
    bernstein_two_regime_rate,
    centered_chi_square_log_mgf,
    centered_chi_square_sum_trials,
    centered_chi_square_sum_upper_tail,
    centered_chi_square_upper_tail,
    centered_pareto_clip_bias,
    empirical_tail_profile,
    moment_growth_profile,
    rademacher_projection_trials,
    standard_normal_maxima,
    subgaussian_max_threshold,
)
from .streaming import (
    MomentState,
    comparison_audit,
    merge_moments,
    naive_moments,
    observation_ledger,
    stable_online_moments,
)

__all__ = [
    "MomentState",
    "MarchenkoPasturSupport",
    "NoisyQuadraticSummary",
    "PowerIterationResult",
    "QuantizationResult",
    "QuadraticTrace",
    "SpectrumSummary",
    "UpdateTrace",
    "bernstein_two_regime_rate",
    "centered_chi_square_log_mgf",
    "centered_chi_square_sum_trials",
    "centered_chi_square_sum_upper_tail",
    "centered_chi_square_upper_tail",
    "centered_pareto_clip_bias",
    "circle_covering_radius",
    "circle_epsilon_net",
    "comparison_audit",
    "covariance_eigenvalues",
    "classify_mode_factors",
    "empirical_tail_profile",
    "empirical_upper_threshold",
    "float_contract",
    "gaussian_covariance_trials",
    "gaussian_singular_value_trials",
    "local_spacing",
    "merge_moments",
    "marchenko_pastur_density",
    "marchenko_pastur_support",
    "matrix_spectrum_summary",
    "moment_growth_profile",
    "naive_moments",
    "observation_ledger",
    "operator_net_certificate",
    "operator_net_estimate",
    "power_iteration_spectral_norm",
    "quadratic_spectrum",
    "quadratic_trace",
    "rademacher_projection_trials",
    "repeated_update",
    "stable_online_moments",
    "scalar_noisy_quadratic_trials",
    "sample_covariance",
    "sphere_cover_log_upper",
    "standard_normal_maxima",
    "stochastic_update_trials",
    "symmetric_quantize",
    "uniform_subgaussian_threshold",
    "subgaussian_max_threshold",
]

__version__ = "0.9.0"
