{
  "hash": "9a205cfe96dc9feb094a4e69ff25f92c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ndescription: \"Why a large collection of random coordinates can remain predictable, and how the MGF, union bound, independent sums, and the sub-Gaussian Orlicz norm define a usable safe zone.\"\nnumber-offset: 4\njupyter: python3\nharness-ref: ch-05\nharness-api: \"0.5\"\nharness-wheel-sha256: \"316959af60076c4c79cf740212c866a155fa78bf9b1cea0ba9a819b90b2d769a\"\nphenomenon_id: c05-simultaneous-safe-zone\nclaim_ids:\n  - c05-simultaneous-control-001\n  - c05-projection-scale-001\nthreads:\n  subgaussian-safe-zone: seed\nlenses:\n  geometric: primary\n  dynamic: quiet\n  algorithmic: supporting\n---\n\n# The Safe Zone Is Logarithmic: Sub-Gaussian Concentration and Simultaneous Control {#c05}\n\n\n<span class=\"thread\">SG · The sub-Gaussian safe zone</span>\n<span class=\"lens-ledger\">Geometric primary · Dynamic quiet · Algorithmic supporting</span>\n\nDraw one standard-normal vector of length $100$, then one of length one\nmillion. In the seeded witness below, their largest magnitudes are $2.50$ and\n$4.71$.\n\nThe number of opportunities grew by ten thousand. The maximum did not.\n\n::: {.callout-important title=\"Prediction\"}\nIf the number of coordinates grows by a factor of ten, should a\n99%-simultaneous deviation threshold:\n\n1. grow by a factor of ten;\n2. grow by a factor of $\\sqrt{10}$; or\n3. increase only through a logarithm?\n\nChoose one, then name the tail assumption your answer needs.\n:::\n\n## A million chances to fail {#sec-c05-opening}\n\nThe study uses one independent random stream per vector length. Each maximum\nis a single seeded witness, not an estimate of the expected maximum. The\ncomparison curve is a theorem-derived threshold at failure probability\n$\\delta=0.01$.\n\n:::: {.plan-code}\n::: {.plan}\n1. Load the chapter-pinned concentration instruments.\n2. Draw one independent standard-normal vector at each declared size.\n3. Compute the simultaneous sub-Gaussian threshold.\n4. Assert the witness remains inside the threshold.\n5. Plot observed maxima against logarithmic and polynomial scales.\n:::\n\n::: {#cell-fig-c05-simultaneous-maxima .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: compare simultaneous-control scales across many random coordinates\"}\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# [1]\n\nfrom trainable_harness import (\n    empirical_tail_profile,\n    moment_growth_profile,\n    rademacher_projection_trials,\n    standard_normal_maxima,\n    subgaussian_max_threshold,\n)\n\n# [2]\ncounts = np.array([100, 1_000, 10_000, 100_000, 1_000_000])\nmaxima = standard_normal_maxima(counts, seed=6214)\nobserved = np.array([maxima[int(count)] for count in counts])\n\n# [3]\ndelta = 0.01\nsafe_threshold = np.array(\n    [subgaussian_max_threshold(int(count), delta) for count in counts]\n)\nvariance_only_threshold = np.sqrt(counts / delta)\n\n# [4]\nassert np.all(observed < safe_threshold)\nbillion_threshold = subgaussian_max_threshold(1_000_000_000, delta)\n\n# [5]\nfig, ax = plt.subplots(figsize=(7.0, 3.8))\nax.loglog(counts, observed, \"o-\", linewidth=2.2, label=\"single seeded maximum\")\nax.loglog(counts, safe_threshold, linewidth=2.2, label=\"sub-Gaussian threshold\")\nax.loglog(\n    counts,\n    variance_only_threshold,\n    linestyle=\"--\",\n    linewidth=1.8,\n    label=\"variance-only threshold\",\n)\nax.set(xlabel=\"number of coordinates\", ylabel=\"simultaneous magnitude\")\nax.grid(alpha=0.25, which=\"both\")\nax.legend(frameon=False)\nplt.show()\n\nprint(f\"harness={manifest['harness_ref']} wheel={manifest['wheel_sha256'][:12]}\")\nfor count, maximum, threshold in zip(counts, observed, safe_threshold):\n    print(f\"m={count:>7}: max={maximum:.4f}, 99%-threshold={threshold:.4f}\")\nprint(f\"billion-coordinate model threshold={billion_threshold:.4f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![Observed coordinate maxima grow slowly across vector sizes from 100 to one million. The sub-Gaussian 99%-simultaneous threshold grows as the square root of a logarithm, while a variance-only union-bound threshold grows as the square root of the count. The observed line is one seeded witness; it does not estimate the expected maximum or certify an unknown distribution's tail class.](05-subgaussian-safe-zone_files/figure-html/fig-c05-simultaneous-maxima-output-1.png){#fig-c05-simultaneous-maxima width=592 height=344 fig-alt='Log-log plot of maximum absolute standard-normal coordinate versus vector length. The observed maxima rise slowly from about 2.5 to 4.7 and remain below a sub-Gaussian threshold rising from 4.45 to 6.18. A variance-only threshold rises much more steeply.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nharness=ch-05 wheel=316959af6007\nm=    100: max=2.4959, 99%-threshold=4.4505\nm=   1000: max=3.0185, 99%-threshold=4.9409\nm=  10000: max=4.0644, 99%-threshold=5.3868\nm= 100000: max=4.4066, 99%-threshold=5.7985\nm=1000000: max=4.7068, 99%-threshold=6.1829\nbillion-coordinate model threshold=7.2141\n```\n:::\n:::\n\n\n::::\n\nThe bound pays for one million opportunities through\n$\\sqrt{\\log(10^6)}$, not $\\sqrt{10^6}$. The final printed number, $7.2141$,\nis a model calculation for one billion independent standard-normal\ncoordinates under the same proxy scale. The code did not generate a billion\nvalues.\n\nThe geometric problem is now precise: we need a tail envelope strong enough\nto survive a union over many quantities, and we need a scale that composes\nunder weighted sums.\n\n## Exponentiate, then optimize {#sec-c05-mgf}\n\nFor a centered real random variable $X$, suppose\n\n$$\n\\E\\!\\left[e^{\\lambda X}\\right]\n\\le\n\\exp\\!\\left(\\frac{\\sigma^2\\lambda^2}{2}\\right)\n\\qquad\n\\text{for every }\\lambda\\in\\mathbb{R}.\n$$ {#eq-c05-mgf-envelope}\n\nWe call $\\sigma$ a **sub-Gaussian MGF proxy scale**. It is an admissible\nenvelope, not automatically the smallest such scale and not automatically\nthe standard deviation.\n\n::: {#thm-c05-mgf-tail phenomenon_id=\"c05-simultaneous-safe-zone\"}\n## MGF envelope implies a Gaussian tail\n\nUnder @eq-c05-mgf-envelope, for every $t\\ge0$,\n\n$$\n\\Pr(|X|\\ge t)\n\\le\n2\\exp\\!\\left(-\\frac{t^2}{2\\sigma^2}\\right).\n$$ {#eq-c05-two-sided-tail}\n:::\n\n### Proof\n\nFor any $\\lambda>0$, monotonicity of the exponential and Markov's inequality\ngive\n\n$$\n\\Pr(X\\ge t)\n=\n\\Pr(e^{\\lambda X}\\ge e^{\\lambda t})\n\\le\ne^{-\\lambda t}\\E[e^{\\lambda X}]\n\\le\n\\exp\\!\\left(\n-\\lambda t+\\frac{\\sigma^2\\lambda^2}{2}\n\\right).\n$$\n\nThe exponent is a quadratic in $\\lambda$, minimized at\n$\\lambda^\\star=t/\\sigma^2$. Substitution gives\n$\\Pr(X\\ge t)\\le e^{-t^2/(2\\sigma^2)}$. Apply the same argument to $-X$ and\nadd the two tail probabilities. $\\square$\n\nThis is the exponential lift: a probability question becomes a\none-dimensional optimization problem. The theorem does not manufacture an\nMGF bound. It tells us what the bound buys once we establish it.\n\nFor a Rademacher sign $\\varepsilon\\in\\{-1,+1\\}$ with equal probabilities,\n\n$$\n\\E[e^{\\lambda\\varepsilon}]\n=\n\\cosh(\\lambda)\n\\le\ne^{\\lambda^2/2}.\n$$ {#eq-c05-rademacher-mgf}\n\nThus a random sign has proxy scale one. The inequality can be proved by\ncomparing the power series or by checking that\n$e^{-\\lambda^2/2}\\cosh(\\lambda)$ decreases for $\\lambda>0$.\n\n## Coefficient energy controls a sum {#sec-c05-sums}\n\nThe usefulness of @eq-c05-mgf-envelope is compositional.\n\n::: {#thm-c05-independent-sum phenomenon_id=\"c05-simultaneous-safe-zone\"}\n## Independent weighted sums\n\nLet $X_1,\\ldots,X_d$ be independent, centered random variables with MGF proxy\nscales $\\sigma_1,\\ldots,\\sigma_d$. For fixed coefficients\n$\\vect{a}\\in\\mathbb{R}^d$,\n\n$$\nS\n:=\n\\sum_{j=1}^d a_jX_j\n$$\n\nhas proxy variance\n\n$$\n\\sigma_S^2\n=\n\\sum_{j=1}^d a_j^2\\sigma_j^2.\n$$ {#eq-c05-weighted-proxy}\n:::\n\n### Proof\n\nIndependence factorizes the MGF:\n\n$$\n\\begin{aligned}\n\\E[e^{\\lambda S}]\n&=\n\\prod_{j=1}^d\n\\E[e^{\\lambda a_jX_j}]\\\\\n&\\le\n\\prod_{j=1}^d\n\\exp\\!\\left(\n\\frac{\\lambda^2a_j^2\\sigma_j^2}{2}\n\\right)\\\\\n&=\n\\exp\\!\\left(\n\\frac{\\lambda^2}{2}\n\\sum_{j=1}^d a_j^2\\sigma_j^2\n\\right).\n\\end{aligned}\n$$\n\nThis is the required envelope. $\\square$\n\nIndependence is doing identifiable work: it turns one MGF into a product.\nWithout it, @eq-c05-weighted-proxy is not licensed.\n\nIf the $X_j$ are Rademacher and\n$a_j=1/\\sqrt{d}$, then\n$\\sum_j a_j^2=1$. The sum keeps proxy scale one at every width. Width alone\ndoes not cause the scalar projection to explode; coefficient energy decides.\n\n## Pay only a logarithm for simultaneous control {#sec-c05-union}\n\n::: {#thm-c05-simultaneous-control phenomenon_id=\"c05-simultaneous-safe-zone\"}\n## Simultaneous sub-Gaussian control\n\nSuppose $X_1,\\ldots,X_m$ each satisfy @eq-c05-two-sided-tail with the same\nproxy scale $\\sigma$. Mutual independence is not required. For any\n$0<\\delta<1$, with probability at least $1-\\delta$,\n\n$$\n\\max_{1\\le j\\le m}|X_j|\n\\le\n\\sigma\\sqrt{2\\log\\!\\left(\\frac{2m}{\\delta}\\right)}.\n$$ {#eq-c05-simultaneous-threshold}\n:::\n\n### Proof\n\nFor any $t\\ge0$, the union bound gives\n\n$$\n\\Pr\\!\\left(\\max_j|X_j|\\ge t\\right)\n\\le\n\\sum_{j=1}^m\\Pr(|X_j|\\ge t)\n\\le\n2m e^{-t^2/(2\\sigma^2)}.\n$$\n\nSet the last expression equal to $\\delta$ and solve for $t$. $\\square$\n\nDependence can make the union bound loose, but it does not invalidate the\nguarantee. Independence was essential for closing weighted sums; it is not\nessential for union-bounding already available marginal tails.\n\n::: {.callout-warning title=\"Named wrong answer: 'A billion variables require a billion-sigma threshold'\"}\nThe number of opportunities appears inside a logarithm under a sub-Gaussian\ntail envelope. The threshold at $m=10^9$ and $\\delta=0.01$ is about\n$7.21\\sigma$, not $10^9\\sigma$. Change the tail class, however, and the\nscaling can change with it.\n:::\n\n::: {#thm-c05-gaussian-lipschitz phenomenon_id=\"c05-simultaneous-safe-zone\"}\n## Gaussian input, nonlinear diagnostic\n\nLet $\\vect{G}\\sim\\mathcal{N}(\\vect{0},\\matr{I}_d)$ and let\n$f:\\mathbb{R}^d\\to\\mathbb{R}$ be $L$-Lipschitz in Euclidean distance, with\n$L>0$. There are universal constants $c,C>0$ such that\n\n$$\n\\norm{f(\\vect{G})-\\E f(\\vect{G})}_{\\psi_2}\\le CL,\n$$\n\nand therefore\n\n$$\n\\Pr\\!\\left(\\left|f(\\vect{G})-\\E f(\\vect{G})\\right|\\ge t\\right)\n\\le 2\\exp\\!\\left(-\\frac{ct^2}{L^2}\\right),\n\\qquad t\\ge0.\n$$ {#eq-c05-gaussian-lipschitz}\n:::\n\n**Proof with pointer.** This is Gaussian concentration, stated in the Orlicz\nform of Vershynin's second-edition Theorem 5.2.3 [@vershynin2026]. The tail form follows from the\n$\\psi_2$ characterization below. The useful extension is not a new exponent\nbut a new object: $f$ can be nonlinear. For example,\n$f(\\vect{x})=\\norm{\\matr{A}\\vect{x}}_2$ is\n$\\norm{\\matr{A}}_{\\mathrm{op}}$-Lipschitz, so its fluctuation around its mean\ninherits a sub-Gaussian scale.\n\nThe theorem controls fluctuation around a declared center; it does not compute\nthat center. Its standard-Gaussian input is also part of the contract. The\nstatement is not a dependence theorem for arbitrary inputs and does not\nextend unchanged to heavy-tailed data.\n\n## Four instruments for the same safe zone {#sec-c05-equivalence}\n\nSometimes the MGF is easy to calculate. Sometimes moments or a tail bound are\nwhat the problem exposes. The following theorem makes those entry points\ninterchangeable at the level of tail class, not at the level of identical\nconstants.\n\n::: {#thm-c05-equivalent-diagnostics phenomenon_id=\"c05-simultaneous-safe-zone\"}\n## Equivalent sub-Gaussian diagnostics\n\nFor a centered real random variable $X$, the following properties are\nequivalent up to universal constant factors:\n\n1. $\\Pr(|X|\\ge t)\\le2e^{-t^2/K_1^2}$ for all $t\\ge0$;\n2. $(\\E|X|^p)^{1/p}\\le K_2\\sqrt{p}$ for every $p\\ge1$;\n3. $\\E e^{X^2/K_3^2}\\le2$;\n4. $\\E e^{\\lambda X}\\le e^{K_4^2\\lambda^2}$ for every real $\\lambda$.\n\nThe best admissible constants $K_1,\\ldots,K_4$ are comparable up to universal\nfactors.\n:::\n\nThe full equivalence is proved in Vershynin's second-edition Proposition 2.6.1\n[@vershynin2026]. One direction is immediate here: property 3 and Markov's\ninequality give\n\n$$\n\\Pr(|X|\\ge t)\n=\n\\Pr\\!\\left(e^{X^2/K_3^2}\\ge e^{t^2/K_3^2}\\right)\n\\le\n2e^{-t^2/K_3^2}.\n$$\n\nThe exponential-square characterization defines the Orlicz norm\n\n$$\n\\norm{X}_{\\psi_2}\n:=\n\\inf\\left\\{\nK>0:\n\\E e^{X^2/K^2}\\le2\n\\right\\}.\n$$ {#eq-c05-psi2-norm}\n\nIt is a population quantity. An empirical moment curve may reveal a violation\nor suggest a regime, but a finite sample cannot certify what happens beyond\nits largest observation.\n\n| Available object | Diagnostic question | Boundary |\n|---|---|---|\n| tail probabilities | does $-\\log\\Pr(|X|\\ge t)$ grow quadratically? | rare tails may be unseen |\n| moments | does $\\norm{X}_p/\\sqrt p$ remain bounded? | high-order estimates are unstable |\n| exponential-square moment | is a candidate $K$ integrable? | sample averages can hide divergence |\n| MGF | is log-MGF bounded by a quadratic for all $\\lambda$? | local-in-$\\lambda$ control gives local tails |\n\n::: {.callout-note title=\"Field note: proxy variance is not variance\"}\nDifferentiating an exact MGF at zero connects its second derivative to\nvariance, so every valid proxy variance is at least the actual variance.\nEquality is special. Record “MGF proxy scale” when that is the object used by\nthe proof.\n:::\n\n## Width without scale explosion {#sec-c05-projection}\n\nThe next study uses independent Rademacher signs and the normalized\ncoefficients $a_j=1/\\sqrt d$. For each width, 20,000 independent projections\nestimate the mean, sample standard deviation, and the two-sided event\n$|S|\\ge2$. Each width receives a separate named seed.\n\n:::: {.plan-code}\n::: {.plan}\n1. Declare widths, trial count, coefficient norm, and seed policy.\n2. Generate normalized Rademacher projections.\n3. Estimate mean, standard deviation, and a two-sided tail probability.\n4. Report estimator uncertainty and assert order-one scale.\n5. Plot scale and tail behavior across widths.\n:::\n\n::: {#cell-fig-c05-projection-scale .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: test coefficient-energy scaling across projection widths\"}\n# [1]\nwidths = np.array([16, 64, 256, 1024])\ntrials = 20_000\nbase_seed = 6215\n\n# [2]\nprojection_samples = {}\nfor index, width in enumerate(widths):\n    coefficients = np.ones(width) / np.sqrt(width)\n    assert np.isclose(np.linalg.norm(coefficients), 1.0)\n    projection_samples[int(width)] = rademacher_projection_trials(\n        coefficients,\n        trials=trials,\n        seed=base_seed + index,\n    )\n\n# [3]\nmeans = np.array([projection_samples[int(width)].mean() for width in widths])\nstandard_deviations = np.array(\n    [projection_samples[int(width)].std(ddof=1) for width in widths]\n)\ntails = np.array(\n    [\n        empirical_tail_profile(\n            projection_samples[int(width)],\n            [2.0],\n        )[2.0]\n        for width in widths\n    ]\n)\n\n# [4]\nmean_standard_errors = standard_deviations / np.sqrt(trials)\nsd_standard_errors = standard_deviations / np.sqrt(2 * (trials - 1))\ntail_standard_errors = np.sqrt(tails * (1 - tails) / trials)\nassert np.all(np.abs(means) < 4 * mean_standard_errors)\nassert np.all(np.abs(standard_deviations - 1) < 0.04)\ntail_upper_bound = 2 * np.exp(-2)\n\n# [5]\nfig, axes = plt.subplots(1, 2, figsize=(8.2, 3.5))\naxes[0].errorbar(\n    widths,\n    standard_deviations,\n    yerr=1.96 * sd_standard_errors,\n    marker=\"o\",\n    linewidth=2,\n    capsize=3,\n)\naxes[0].axhline(1.0, color=\"black\", linestyle=\"--\", label=\"theoretical scale\")\naxes[0].set(xlabel=\"width\", ylabel=\"sample standard deviation\")\naxes[1].errorbar(\n    widths,\n    tails,\n    yerr=1.96 * tail_standard_errors,\n    marker=\"o\",\n    linewidth=2,\n    capsize=3,\n    label=r\"empirical $\\Pr(|S|\\geq2)$\",\n)\naxes[1].axhline(\n    tail_upper_bound,\n    color=\"black\",\n    linestyle=\"--\",\n    label=\"sub-Gaussian upper bound\",\n)\naxes[1].set(xlabel=\"width\", ylabel=\"probability\")\nfor ax in axes:\n    ax.set_xscale(\"log\", base=2)\n    ax.grid(alpha=0.25)\n    ax.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n\nfor index, width in enumerate(widths):\n    print(\n        f\"d={width:>4}: mean={means[index]: .5f} \"\n        f\"(SE {mean_standard_errors[index]:.5f}), \"\n        f\"sd={standard_deviations[index]:.5f}, \"\n        f\"P(|S|>=2)={tails[index]:.5f}\"\n    )\n```\n\n::: {.cell-output .cell-output-display}\n![Normalized Rademacher projections retain sample standard deviation near one from width 16 through 1024, as predicted by coefficient energy. The empirical event probability for absolute projection at least two varies with the finite lattice and approaches the Gaussian-like regime; the loose sub-Gaussian upper bound is shown only as a guarantee.](05-subgaussian-safe-zone_files/figure-html/fig-c05-projection-scale-output-1.png){#fig-c05-projection-scale width=780 height=325 fig-alt='Two-panel plot across widths 16, 64, 256, and 1024. The left panel shows sample standard deviations with error bars clustered near the horizontal reference value one. The right panel shows empirical tail probabilities decreasing toward about 0.048, below a horizontal sub-Gaussian upper bound near 0.271.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nd=  16: mean= 0.01333 (SE 0.00710), sd=1.00381, P(|S|>=2)=0.07675\nd=  64: mean=-0.00676 (SE 0.00705), sd=0.99644, P(|S|>=2)=0.05905\nd= 256: mean= 0.00569 (SE 0.00706), sd=0.99901, P(|S|>=2)=0.05200\nd=1024: mean= 0.00829 (SE 0.00705), sd=0.99730, P(|S|>=2)=0.04785\n```\n:::\n:::\n\n\n::::\n\nThe sample standard deviations range from about $0.996$ to $1.004$. That is\nevidence for this seeded protocol, with approximate standard error about\n$0.005$ for each standard deviation. The theorem explains why the scale\nshould remain order one: $\\norm{\\vect{a}}_2=1$ at every width.\n\nThe tail bound $2e^{-2}\\approx0.271$ is deliberately loose. It is a valid\nenvelope, not a prediction of the exact tail probability.\n\n## Geometry meets the finite grid {#sec-c05-hardware}\n\nSuppose a computation produces $m$ centered scalar quantities with proxy scale\n$\\sigma$. Equation @eq-c05-simultaneous-threshold gives a high-probability\nenvelope for their maximum. C03 then asks whether that envelope fits the\ndeclared storage range and whether the sums forming each quantity use an\nadequate accumulator.\n\nFor $m=10^9$, $\\delta=0.01$, and $\\sigma=1$, the model threshold $7.21$ is\nfar below FP16's largest finite value. That statement alone does **not**\nguarantee safe training:\n\n- the proxy scale may drift;\n- coordinates may cease to be sub-Gaussian;\n- depth can multiply scales;\n- intermediate reductions can overflow even when outputs do not;\n- an implementation can change the accumulation contract.\n\nThe safe zone is a diagnostic hypothesis with a numerical consequence, not a\nbranding phrase. C14 will derive when initialization keeps the coefficient\nenergy controlled across depth. C06 has the nearer obligation: it will square\na sub-Gaussian quantity and show why the same tail model no longer applies.\n\n::: {.callout-tip title=\"Check yourself\"}\nLet $m=10^7$, $\\delta=10^{-3}$, and proxy scale $\\sigma=0.5$. Compute the\nsimultaneous threshold from @eq-c05-simultaneous-threshold. If all variables\nare identical copies of the same random variable rather than independent,\ndoes the theorem remain valid? Which earlier proof step changes?\n:::\n\n## Okay, so —\n\n- **Inherited:** C03 supplied the range/accumulation contract, and C04 showed\n  why controlling one direction is not enough when many modes coexist.\n- **Changed:** Randomness is now described by a tail class and proxy scale\n  that can survive simultaneous control.\n- **Instrumented:** The harness computes simultaneous thresholds, seeded\n  maxima, weighted-sign projections, empirical tails, and moment-growth\n  profiles.\n- **Established:** A quadratic MGF envelope yields Gaussian tail decay,\n  independent weighted sums add proxy variances, a union bound charges only\n  $\\sqrt{\\log m}$, and Lipschitz diagnostics of a standard Gaussian input\n  concentrate around their own means.\n- **Unresolved:** Which tail class replaces global sub-Gaussian control after\n  a square or product changes the moment-generating function?\n\n## Sources and further reading\n\nChernoff's exponential method supplies the optimization view of tail bounds\n[@chernoff1952]. Hoeffding develops probability inequalities for sums of\nbounded independent variables [@hoeffding1963]. Vershynin gives the modern\nsub-Gaussian equivalence, Orlicz norm, and Gaussian Lipschitz concentration\nused here [@vershynin2026].\n\nFor the general theory, use @vershynin2026; this chapter's contribution is\nthe precision-facing safe-zone diagnostic and its explicit failure boundary.\n\n**Reading order.** Start with @vershynin2026 for the reusable equivalences,\nthen read @chernoff1952 and @hoeffding1963 for the original exponential-method\nand bounded-sum viewpoints.\n\n## Exercises\n\n1. **(Pencil.) Optimize the exponent.** Repeat the proof of\n   @thm-c05-mgf-tail when the MGF bound is known only for\n   $|\\lambda|\\le\\lambda_0$. Derive the range of $t$ in which the quadratic\n   optimizer remains admissible and state what happens outside it.\n\n2. **(Pencil.) Dependence audit.** Give two examples with identical\n   sub-Gaussian marginals: one with independent coordinates and one with all\n   coordinates equal. Compare their exact maxima and the common union-bound\n   guarantee. Explain why validity and sharpness are separate questions.\n\n3. **(Code.) Maxima as an estimator.** Replace the single opening witness with\n   repeated maxima at each feasible count. Predeclare trial counts, report the\n   empirical median and a quantile interval, and keep the total draw budget\n   fixed across design choices.\n\n4. **(Code.) Coefficient geometry.** Compare three coefficient sequences:\n   uniform $1/\\sqrt d$, one-spike, and geometrically decaying, all normalized\n   to the same $\\ell_2$ norm. Measure tails and explain what the MGF theorem\n   predicts identically and what the exact distributions retain.\n\n5. **(Audit.) The empirical certificate.** A report computes\n   $\\norm{X}_p/\\sqrt p$ for $p\\le8$ on 10,000 observations and declares the\n   population sub-Gaussian. Predict a contamination distribution that is\n   likely to evade the sample, then state a defensible empirical conclusion.\n\n6. **(Audit.) Paper audit: Hoeffding's bounded-sum inequality.** Complete the\n   **Mathematical object**, **Evidence culture and interface**, **Assumption\n   stress test**, and **Transfer verdict** fields for the primary paper and extract the independence assumption, the bounded-range\n   quantity, and the tail exponent for a weighted sum. Map each object to the\n   MGF proxy language of this chapter and identify any constant or scope that\n   cannot be transferred verbatim.\n\n",
    "supporting": [
      "05-subgaussian-safe-zone_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}