{
  "hash": "2dccff470cf89d5d56bebd71098d0b9a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nsubtitle: \"Arithmetic intensity, the memory hierarchy, and honest performance claims\"\ndescription: \"Why an operation count cannot identify the resource that sets elapsed time.\"\nnumber-offset: 0\njupyter: python3\nphenomenon_id: c01-count-not-cost\nclaim_ids: [c01-roofline-001, c01-local-measurement-001]\nthreads: {}\nlenses:\n  geometric: quiet\n  dynamic: supporting\n  algorithmic: primary\n---\n\n# The Count Is Not the Cost {#c01}\n\n<span class=\"lens-ledger\">Geometric quiet · Dynamic supporting · Algorithmic primary</span>\n\nConsider two computations on $N$ stored FP32 values. A copy performs no\nfloating-point arithmetic and moves at least $8N$ bytes: one read and one\nwrite. A fused affine transform $y_i=ax_i+b$ performs $2N$ floating-point\noperations and has the same dominant traffic when $a$ and $b$ remain in a\nfast store. One count is zero; the ratio is not the point. Their bandwidth\nceilings are essentially the same.\n\nNow compare a square matrix product of order $n=512$. The conventional count\nis $2n^3$ operations. Its compulsory traffic under an idealized one-read,\none-write model is $12n^2$ bytes, so its arithmetic intensity is\n$n/6=85.33$ operations per byte. The affine transform has intensity $2/8=0.25$.\nOn a hypothetical machine whose peak arithmetic-to-bandwidth ratio is 20,\none falls below the balance point and the other lies above it. The larger\noperation count can be the computation with more opportunity to reuse data.\n\n::: {.callout-important title=\"Prediction\"}\nOn one fixed machine, a proposed method halves the multiplications and doubles\ncompulsory traffic. Choose a prediction before continuing: **faster**,\n**slower**, or **undetermined**. Which traffic boundary and machine balance\nwould let you defend that choice?\n:::\n\n## Two resource clocks {#sec-c01-two-clocks}\n\nLet $F$ be the required operations, $Q$ the bytes transferred through a\ndeclared boundary, $P_{\\max}$ peak arithmetic rate, and $B$ peak bandwidth.\nThe two unavoidable time lower bounds are\n\n$$\nT\\geq \\frac{F}{P_{\\max}},\\qquad T\\geq\\frac{Q}{B}.\n$$ {#eq-c01-resource-times}\n\nWith arithmetic intensity $I=F/Q$, achieved performance $P=F/T$ obeys the\nfollowing deliberately small theorem.\n\n::: {#thm-c01-roofline phenomenon_id=\"c01-count-not-cost\"}\n### Two-resource performance ceiling\n\nUnder the declared operation count, traffic boundary, peak arithmetic rate,\nand peak bandwidth,\n\n$$\nP\\leq \\min(P_{\\max},BI).\n$$ {#eq-c01-roofline}\n:::\n\n### Proof\n\nInvert each inequality in @eq-c01-resource-times and multiply by $F$. The\narithmetic bound gives $P\\leq P_{\\max}$; the traffic bound gives\n$P\\leq BF/Q=BI$. Both must hold.\n\nThe bend occurs at the **machine balance** $I_*=P_{\\max}/B$. This diagram is\nthe roofline model [@williams2009]. It is an upper envelope, not a prediction\nthat a kernel reaches either roof.\n\n:::: {.plan-code}\n::: {.plan}\n1. Read the committed C01 model calculation.\n2. Declare one hypothetical machine balance.\n3. Plot the bandwidth and arithmetic ceilings.\n4. Place the vector transform and matrix product on the same axes.\n5. Check the registered arithmetic intensities before interpretation.\n:::\n\n::: {.cell execution_count=1}\n``` {.python .cell-code code-summary=\"Code: place two exact traffic models on a declared roofline\"}\nimport json\nfrom pathlib import Path\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# [1]\nclaim = json.loads(Path(\"artifacts/claims/c01-roofline-001.json\").read_text())\n# [2]\nbalance = claim[\"result\"][\"machine_balance_flop_per_byte\"]\n# [3]\nintensity = np.logspace(-2, 3, 300)\nceiling = np.minimum(intensity / balance, 1.0)\nfig, axis = plt.subplots(figsize=(7.2, 3.8))\naxis.loglog(intensity, ceiling, color=\"#232D4B\", linewidth=2)\n# [4]\npoints = {\n    \"fused affine\": claim[\"result\"][\"vector_affine_intensity\"],\n    \"512×512 product\": claim[\"result\"][\"gemm_intensity\"],\n}\nfor label, value in points.items():\n    axis.scatter(value, min(value / balance, 1.0), s=55)\n    axis.annotate(\n        label,\n        (value, min(value / balance, 1.0)),\n        xytext=(5, 8),\n        textcoords=\"offset points\",\n    )\naxis.set(\n    xlabel=\"arithmetic intensity (operation/byte)\",\n    ylabel=\"fraction of arithmetic peak\",\n)\naxis.grid(True, which=\"both\", alpha=0.25)\nfig.tight_layout()\n# [5]\nassert np.isclose(points[\"fused affine\"], 0.25)\nassert np.isclose(points[\"512×512 product\"], 512 / 6)\nprint(\"claim c01-roofline-001: verified\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nclaim c01-roofline-001: verified\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![One operation count is not one cost. Under the declared two-resource model, the vector transform lies below the balance point while the reused matrix product lies above it.](01-count-not-cost_files/figure-pdf/fig-c01-roofline-output-2.pdf){#fig-c01-roofline fig-alt='Log-log roofline chart with a sloped bandwidth ceiling meeting a flat arithmetic ceiling at intensity 20. The vector transform is at intensity 0.25 on the sloped branch; the order-512 matrix product is at intensity about 85 on the flat branch.' fig-pos='H'}\n:::\n:::\n\n\n::::\n\n## A zero-count kernel still consumes a clock {#sec-c01-local-witness}\n\nThe model now needs a measured control. The committed observation times a\n64 MiB FP32 payload copy and an order-512 FP32 matrix product on one Apple M4\nMax CPU. It also sweeps nearby sizes to establish two **local empirical\nceilings** in the same process. Those ceilings are not vendor peaks. They are\nreference rates that make the achieved fractions inspectable without claiming\nthat a laptop CPU represents an accelerator.\n\n:::: {.plan-code}\n::: {.plan}\n1. Read the pinned local measurement and its protocol.\n2. Extract the selected copy and matrix-product rates.\n3. Normalize each rate by its own local empirical ceiling.\n4. Plot resource-specific fractions rather than a false common unit.\n5. Check that the displayed values match the committed observation.\n:::\n\n::: {.cell execution_count=2}\n``` {.python .cell-code code-summary=\"Code: inspect a pinned CPU copy and matrix-product measurement\"}\n# [1]\nmeasurement = json.loads(\n    Path(\"artifacts/claims/c01-local-measurement-001.json\").read_text()\n)\nprotocol = measurement[\"measurement_contract\"]\n\n# [2]\ncopy_result = measurement[\"result\"][\"copy_by_mib\"][\"64\"]\nmatmul_result = measurement[\"result\"][\"matmul_by_order\"][\"512\"]\n\n# [3]\nfractions = np.array([\n    measurement[\"result\"][\"copy_64_fraction_of_local_bandwidth_ceiling\"],\n    measurement[\"result\"][\"matmul_512_fraction_of_local_arithmetic_ceiling\"],\n])\n\n# [4]\nfig, axis = plt.subplots(figsize=(7.2, 2.8))\naxis.barh(\n    [\"64 MiB copy\", \"order-512 product\"],\n    fractions,\n    color=[\"#9C2F2F\", \"#232D4B\"],\n)\naxis.set(\n    xlim=(0, 1.08),\n    xlabel=\"fraction of the matching local empirical ceiling\",\n)\naxis.grid(axis=\"x\", alpha=0.22)\nfig.tight_layout()\n\n# [5]\nassert protocol[\"statistic\"] == \"median elapsed time\"\nassert np.isclose(copy_result[\"median_seconds\"], 0.000947375)\nassert np.isclose(matmul_result[\"median_seconds\"], 0.0001039795)\nprint(\n    f\"copy: {1e3 * copy_result['median_seconds']:.3f} ms; \"\n    f\"{copy_result['achieved_gbyte_per_second']:.1f} GB/s\"\n)\nprint(\n    f\"matmul: {1e3 * matmul_result['median_seconds']:.3f} ms; \"\n    f\"{matmul_result['achieved_gflop_per_second']:.1f} GFLOP/s\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncopy: 0.947 ms; 141.7 GB/s\nmatmul: 0.104 ms; 2581.6 GFLOP/s\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![A zero-FLOP copy has a positive measured cost. Each bar is normalized by a separately measured local ceiling for its own resource, so the figure supports a resource diagnosis rather than a cross-kernel speed ranking.](01-count-not-cost_files/figure-pdf/fig-c01-local-measurement-output-2.pdf){#fig-c01-local-measurement fig-alt='Two horizontal bars. The 64 MiB copy reaches about 0.875 of the local empirical bandwidth ceiling, while the order-512 matrix product reaches the local empirical arithmetic ceiling.' fig-pos='H'}\n:::\n:::\n\n\n::::\n\nThe copy moved a 64 MiB payload across the declared read-plus-write boundary,\nso the traffic count was 128 MiB. Its median time was about $0.947$ ms and its\nachieved bandwidth was $141.7$ GB/s, or $87.5\\%$ of the best copy rate in the\ndeclared size sweep. The matrix product reached $2581.6$ GFLOP/s in the same\nsoftware process. These observations do not say that one kernel is generally\nfaster: they show that zero counted arithmetic does not mean zero elapsed\ntime, and that each kernel must be compared with the roof for the resource it\nactually demands.\n\n## The denominator is an algorithmic choice {#sec-c01-denominator}\n\nTraffic has no meaning until its boundary is named. Bytes between registers\nand a first-level cache, between cache and main memory, and between host and\naccelerator are different denominators. Tiling changes $Q$ by retaining a\nworking set near arithmetic units. Fusion changes $Q$ by keeping an\nintermediate value from making a round trip. Recompute can deliberately\nincrease $F$ to reduce $Q$. C11 will return to exactly that trade when it\ncheckpoints derivative state.\n\nThis also foreshadows the numerical-stability thread that C02 seeds. A fused operation can change\nboth traffic and rounding: eliminating an intermediate store may eliminate\none rounding step. A performance transformation is therefore part of the\nnumerical contract, not merely a scheduling detail.\n\n::: {.callout-warning title=\"Named wrong answer: fewer operations means faster\"}\nFewer operations is evidence only after the limiting resource is identified.\nIt may improve a compute-limited kernel, do nothing to a bandwidth-limited\nkernel, or make the kernel slower by destroying reuse or fusion.\n:::\n\n## Hardware-claim boundary {#sec-c01-boundary}\n\nThe roofline is useful because it makes omissions visible. Peak values may be\nunreachable; compulsory traffic can underestimate actual traffic; latency,\nlaunch overhead, synchronization, occupancy, instruction mix, and access\nregularity remain outside @eq-c01-roofline. CPU simulation of FP16 behavior is\nnot evidence of accelerator timing. Any measured claim later in this book\nmust name the device, software stack, warmup, repetitions, statistic, and\ntraffic boundary—or be labeled a model calculation or pinned artifact.\n\n::: {.callout-tip title=\"Field note: read a speedup claim in three passes\"}\nFirst locate the mathematical work and the denominator behind its reported\nrate. Then locate the resource boundary: bytes, arithmetic, latency,\ncommunication, or some mixture. Only then compare measured elapsed time,\nincluding baseline, device, precision, warmup, repetitions, statistic, and\nfailure accounting. A speedup is an observation about that full comparison,\nnot a synonym for a smaller operation count.\n:::\n\n## Check yourself {#sec-c01-check}\n\nA kernel performs $10^{10}$ operations and moves $10^9$ bytes. On a device\nwith $P_{\\max}=10^{13}$ operation/s and $B=5\\times10^{11}$ byte/s, its\nwhat are its intensity, machine balance, active roofline branch, and model\nceiling? If $F$ is halved while $Q$ is unchanged, which lower bound changes\nand which one does not?\n\n## Okay, so — {#sec-c01-recap}\n\n- **Inherited:** asymptotic operation counts remain indispensable scaling summaries.\n- **Changed:** elapsed-time reasoning now requires a declared traffic denominator and machine balance.\n- **Instrumented:** one exact roofline claim and one pinned laptop measurement separate modeled ceilings from achieved rates.\n- **Established:** $P\\leq\\min(P_{\\max},BI)$ follows from two resource lower bounds.\n- **Unresolved:** real executions move more state through more levels; C02 asks which state an online computation must retain.\n\n## Sources and further reading {#sec-c01-sources}\n\nThe roofline formulation and its machine-balance interpretation follow\n@williams2009.\n\n## Exercises {#sec-c01-exercises}\n\n1. **(Pencil.)** Recompute the matrix-product intensity if one input matrix is reread four times. State the traffic boundary.\n2. **(Code.)** For three hypothetical machine balances, redraw the figure and report which classifications change. Do not time the plotting code.\n3. **(Pencil.)** A checkpointing rule adds $30\\%$ arithmetic and removes half the retained-state traffic. Derive the intensities before and after, then state the machine-balance range in which the trade can improve the roofline bound.\n4. **(Code.)** Re-run the local protocol with three payload sizes and three matrix orders. Declare device, stack, warmup, repetitions, statistic, and traffic boundary. Compare medians and dispersion; do not call the best observed rate a vendor peak.\n5. **(Audit.) Paper audit:** Find one reported speedup and complete the **Claim**, **Mathematical object**, **Evidence culture and interface**, **Numerical and hardware contract**, and **Transfer verdict** fields of the Paper Autopsy Protocol. Separate operation count, modeled traffic, measured elapsed time, hardware identity, and baseline. Which claim is actually supported?\n\n",
    "supporting": [
      "01-count-not-cost_files/figure-pdf"
    ],
    "filters": []
  }
}