{
  "hash": "772971bc2e1baf3764a340aa03cec6f6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nsubtitle: \"Range, resolution, and rounding\"\ndescription: \"Why a nonzero update can become identically zero, and how a complete precision contract separates range, representation, arithmetic, cancellation, and scale allocation.\"\nnumber-offset: 2\njupyter: python3\nharness-ref: ch-03\nharness-api: \"0.3\"\nharness-wheel-sha256: \"833cfe618f0ca4869424c1832361c7f8281e63a32934ad8e9b14bc391db89918\"\nphenomenon_id: c03-vanishing-update\nclaim_ids:\n  - c03-update-stagnation-001\n  - c03-format-envelope-001\n  - c03-grid-collapse-001\n  - c03-stochastic-rounding-001\nthreads:\n  numerical-stability: callback\nlenses:\n  geometric: supporting\n  dynamic: supporting\n  algorithmic: primary\nfulfills:\n  - promise-c02-c03-loss-boundary\n  - promise-c02-c03-precision-contract\n---\n\n# The Grid Under the Update {#c03}\n\n<span class=\"thread\">NS · Numerical stability</span>\n<span class=\"lens-ledger\">Geometric supporting · Dynamic supporting · Algorithmic primary</span>\n\nA parameter is stored as FP16 at the value $1024$. An algorithm asks for the\nsame update, $+0.25$, four hundred times. Exact arithmetic ends at $1124$.\nThe stored parameter never moves.\n\nNothing overflowed. The update was not zero. The code executed all four\nhundred additions. Yet every requested change disappeared.\n\n::: {.callout-important title=\"Prediction\"}\nWhich boundary swallowed the update?\n\n1. The value left the format's range.\n2. The input $0.25$ could not be represented.\n3. The addition produced a result that rounded back to $1024$.\n4. Positive and negative quantities catastrophically cancelled.\n\nChoose one, then name the control that would separate it from the others.\n:::\n\n## The update that never lands {#sec-c03-opening}\n\nThe opening witness is a format simulation on a CPU. It makes a statement\nabout FP16 rounding, not about CPU or accelerator speed. The chapter verifies\nand imports its own vendored harness wheel, so later changes to the package\ncannot silently alter this result.\n\n:::: {.plan-code}\n::: {.plan}\n1. Verify and activate the chapter's exact harness wheel.\n2. Request four hundred $+0.25$ updates from the same initial value.\n3. Record the local spacing and the full precision contract.\n4. Assert the stalled stored path against the exact path.\n:::\n\n::: {.cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: expose a nonzero update that never changes stored state\"}\nfrom hashlib import sha256\nimport json\nfrom pathlib import Path\nimport sys\n\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# [1]\nmanifest_path = Path(\"artifacts/harness/ch-03/manifest.json\")\nmanifest = json.loads(manifest_path.read_text())\nwheel_path = manifest_path.parent / manifest[\"wheel\"]\nassert sha256(wheel_path.read_bytes()).hexdigest() == manifest[\"wheel_sha256\"]\nsys.path.insert(0, str(wheel_path.resolve()))\n\nfrom trainable_harness import (\n    float_contract,\n    local_spacing,\n    repeated_update,\n    stochastic_update_trials,\n    symmetric_quantize,\n)\n\n# [2]\ninitial, increment, steps = 1024.0, 0.25, 400\ntrace = repeated_update(initial, increment, steps, dtype=np.float16)\n\n# [3]\nspacing = local_spacing(initial, dtype=np.float16)\nprecision_ledger = {\n    \"storage\": \"float16\",\n    \"operands\": \"exactly representable float16 inputs\",\n    \"compute\": \"correctly rounded binary addition\",\n    \"accumulator\": \"stored state itself\",\n    \"output\": \"float16 after every step\",\n    \"rounding\": \"nearest, ties to even\",\n}\n\n# [4]\nassert trace.exact_final == 1124.0\nassert trace.final == 1024.0\nassert trace.changed_steps == 0\n\nfig, ax = plt.subplots(figsize=(7.0, 3.8))\nax.plot(trace.exact, color=\"#232D4B\", linewidth=2.2, label=\"Exact requested path\")\nax.plot(trace.stored, color=\"#9C2F2F\", linewidth=2.2, label=\"Stored FP16 path\")\nax.set(xlabel=\"update step\", ylabel=\"state\")\nax.grid(alpha=0.25)\nax.legend(frameon=False)\nplt.show()\n\nprint(f\"harness={manifest['harness_ref']} wheel={manifest['wheel_sha256'][:12]}\")\nprint(f\"local spacing={spacing:g}; half spacing={spacing / 2:g}\")\nprint(f\"exact endpoint={trace.exact_final:g}; stored endpoint={trace.final:g}\")\n```\n\n::: {.cell-output .cell-output-display}\n![A requested update of 0.25 advances the exact trajectory but never changes an FP16 value stored at 1024. The figure supports a local-resolution diagnosis under the declared round-after-each-step contract; it is not a hardware timing result.](03-precision-contract_files/figure-pdf/fig-c03-stalled-update-output-1.pdf){#fig-c03-stalled-update fig-alt='Line plot over 400 update steps. The exact trajectory rises from 1024 to 1124, while the FP16 stored trajectory remains horizontal at 1024.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nharness=ch-03 wheel=833cfe618f0c\nlocal spacing=1; half spacing=0.5\nexact endpoint=1124; stored endpoint=1024\n```\n:::\n:::\n\n\n::::\n\nThe value $0.25$ is exactly representable in binary. The exact sum\n$1024.25$ is also far inside the finite range of FP16. The failure occurs\nwhen that sum must be stored back on the local FP16 grid. Its neighbors are\n$1024$ and $1025$; round-to-nearest returns $1024$. The next step starts\nfrom the same state and repeats the same loss.\n\nThis is stagnation by local resolution. Describing the computation only as\n“FP16” does not reveal it. We needed the state value, update size, storage\npoint, and rounding rule.\n\n## A floating format is a changing grid {#sec-c03-local-grid}\n\nA normalized radix-two value with $p$ significand bits has the form\n\n$$\nx\n=\n\\pm\\left(1.b_1b_2\\cdots b_{p-1}\\right)_2 2^e.\n$$ {#eq-c03-normal-form}\n\nThe leading one is fixed for normal values. Incrementing the last stored bit\nchanges the significand by $2^{-(p-1)}$, then the exponent scales that\nchange by $2^e$.\n\n::: {#thm-c03-binade-spacing phenomenon_id=\"c03-vanishing-update\"}\n## Binade spacing\n\nIn a normalized radix-two format with $p$ significand bits, consecutive\nrepresentable values in the binade $[2^e,2^{e+1})$ differ by\n\n$$\n\\Delta_e=2^{e-(p-1)}.\n$$ {#eq-c03-binade-spacing}\n\nUnder round-to-nearest, an update from a representable value cannot change the\nstored result unless the exact result reaches a midpoint between grid points,\nwith the midpoint itself decided by the tie rule.\n:::\n\n### Proof\n\nWithin one binade, the exponent $e$ is fixed. The stored significands are\n\n$$\n1+\\frac{k}{2^{p-1}},\n\\qquad\nk=0,1,\\ldots,2^{p-1}-1.\n$$\n\nConsecutive values therefore differ by\n\n$$\n2^e\n\\left[\n\\left(1+\\frac{k+1}{2^{p-1}}\\right)\n-\n\\left(1+\\frac{k}{2^{p-1}}\\right)\n\\right]\n=2^{e-(p-1)}.\n$$\n\nRound-to-nearest assigns every exact value between two adjacent midpoints to\nthe enclosed grid point. A smaller perturbation cannot cross that cell's\nboundary. $\\square$\n\nFor FP16, $p=11$. At $1024=2^{10}$,\n@eq-c03-binade-spacing gives\n\n$$\n\\operatorname{ulp}(1024)=2^{10-(11-1)}=1.\n$$\n\nThe update $0.25$ is only one quarter of the local spacing and one half of\nthe distance to the rounding boundary.\n\n### Three nearby quantities that are not synonyms\n\n- $\\operatorname{ulp}(x)$ is a **local** grid spacing near $x$.\n- Machine epsilon, $\\varepsilon_{\\mathrm{mach}}$, is the gap from $1$ to\n  the next larger representable value.\n- For round-to-nearest in a normal binade, the unit roundoff is\n  $u=\\varepsilon_{\\mathrm{mach}}/2$.\n\nThe conventional one-operation model is\n\n$$\n\\operatorname{fl}(z)=z(1+\\delta),\n\\qquad |\\delta|\\le u.\n$$ {#eq-c03-standard-model}\n\nIt applies when one exact result $z$ is correctly rounded to a normal finite\nvalue. It is not a license to ignore overflow, gradual underflow, multiple\noperations, an already-rounded input, or an unspecified reduction.\n\n::: {.callout-warning title=\"Named wrong answer: 'Machine epsilon is the smallest number the format can store'\"}\nMachine epsilon describes the gap after one. The smallest positive normal and\nthe smallest positive subnormal describe range near zero. Local spacing grows\nwith the exponent. One number cannot stand in for all three.\n:::\n\n## Range and resolution are separate budgets {#sec-c03-range}\n\nThe next instrument queries the format instead of relying on remembered\ndecimal approximations.\n\n:::: {.plan-code}\n::: {.plan}\n1. Query the FP16 and FP32 format contracts at runtime.\n2. Separate significand allocation from exponent allocation.\n3. Report epsilon, unit roundoff, and both lower range boundaries.\n4. Verify the observed spacing at the opening state.\n:::\n\n::: {#c03-format-contract .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: inspect range and resolution as separate fields\"}\n# [1]\ncontracts = {\n    \"FP16\": float_contract(np.float16),\n    \"FP32\": float_contract(np.float32),\n}\n\n# [2]\nfor name, contract in contracts.items():\n    print(\n        f\"{name}: significand={contract['significand_bits']} bits, \"\n        f\"exponent={contract['exponent_bits']} bits\"\n    )\n\n# [3]\nfor name, contract in contracts.items():\n    print(\n        f\"{name}: eps={contract['epsilon']:.8g}, \"\n        f\"u={contract['unit_roundoff']:.8g}\"\n    )\n    print(\n        f\"  normal floor={contract['smallest_normal']:.8g}, \"\n        f\"smallest subnormal={contract['smallest_subnormal']:.8g}, \"\n        f\"largest finite={contract['largest_finite']:.8g}\"\n    )\n\n# [4]\nassert contracts[\"FP16\"][\"unit_roundoff\"] == 2**-11\nassert local_spacing(1024.0, dtype=np.float16) == 1.0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFP16: significand=11 bits, exponent=5 bits\nFP32: significand=24 bits, exponent=8 bits\nFP16: eps=0.0009765625, u=0.00048828125\n  normal floor=6.1035156e-05, smallest subnormal=5.9604645e-08, largest finite=65504\nFP32: eps=1.1920929e-07, u=5.9604645e-08\n  normal floor=1.1754944e-38, smallest subnormal=1.4012985e-45, largest finite=3.4028235e+38\n```\n:::\n:::\n\n\n::::\n\nIncreasing exponent bits extends the range; increasing significand bits\nrefines the grid within a binade. Those are different resources. A value can\nbe finite but too coarsely resolved for the update applied to it. Conversely,\na computation can have fine relative resolution throughout its normal range\nand still overflow because that range is too short.\n\nSubnormal values extend the grid below the smallest normal with reduced\nrelative precision. A system may also change their execution behavior. The\nportable claim is therefore not merely a smallest-positive number: the\ncontract must say whether subnormals are supported or flushed.\n\n::: {.callout-note title=\"Field note: a dtype name leaves four blanks\"}\nRecord **storage**, **compute**, **accumulation**, and **output** dtypes\nseparately. Then record the rounding rule and exceptional-value behavior. A\nreduction can read narrow operands, multiply in one format, accumulate in a\nwider format, and round to a narrow output. Calling the entire path “FP16”\nhides the operation most likely to fail.\n:::\n\nThis chapter simulates the declared rounding contract on a CPU. It never uses\nCPU FP16 timing as evidence about accelerator performance.\n\n## Two losses that no longer look alike {#sec-c03-loss-boundary}\n\nChapter 2 separated two failures:\n\n1. distinctions can disappear when real inputs are represented on a grid;\n2. represented inputs can survive, while the evaluation path destroys the\n   desired result.\n\nLocal spacing now makes the first boundary quantitative. If two real values\nround to the same stored value, no later algorithm can infer which one\narrived. Wider accumulation begins too late.\n\nCancellation is different. Suppose $x$ and $y$ are close, but the\nrepresented operands satisfy\n\n$$\n\\widehat{x}=x(1+\\delta_x),\n\\qquad\n\\widehat{y}=y(1+\\delta_y),\n\\qquad\n|\\delta_x|,|\\delta_y|\\le u.\n$$\n\n::: {#thm-c03-cancellation phenomenon_id=\"c03-vanishing-update\"}\n## Cancellation amplification\n\nIf $x\\ne y$, then even before rounding the subtraction itself,\n\n$$\n\\frac{\n\\left|(\\widehat{x}-\\widehat{y})-(x-y)\\right|\n}{\n|x-y|\n}\n\\le\nu\\frac{|x|+|y|}{|x-y|}.\n$$ {#eq-c03-cancellation-bound}\n:::\n\n### Proof\n\nSubstitute the represented operands:\n\n$$\n\\begin{aligned}\n(\\widehat{x}-\\widehat{y})-(x-y)\n&=x\\delta_x-y\\delta_y.\n\\end{aligned}\n$$\n\nThe triangle inequality gives\n\n$$\n\\left|x\\delta_x-y\\delta_y\\right|\n\\le u(|x|+|y|).\n$$\n\nDivide by the nonzero exact difference $|x-y|$. $\\square$\n\nWhen $|x-y|$ is tiny compared with $|x|+|y|$, the subtraction exposes\nerrors that were small relative to the operands but large relative to the\nanswer. Performing that final subtraction in a wider format does not restore\nbits already lost while the two operands were formed.\n\nThis closes the first promise from Chapter 2. Its raw moments occupied the\nscale of $\\mu^2$, and their rounded values differed by exactly one\n$\\operatorname{ulp}(\\mu^2)=32$. The impossible variance was therefore\n$-32$, while the centered algorithms avoided constructing those two large\nnearby operands. At a still larger offset, distinct deviations eventually map\nto the same FP32 input; that later representation loss is irrecoverable.\n\nThe bound in @eq-c03-cancellation-bound is a diagnostic sensitivity statement.\nIt does not include the addition count, reduction tree, fused operations, or\naccumulator format of a complete kernel. Those belong in the precision\ncontract.\n\n## Resolution must be allocated {#sec-c03-quantization}\n\nA finite grid is not merely chosen; it is placed. Consider a signed\n$b$-bit symmetric integer grid with\n\n$$\nq_{\\max}=2^{b-1}-1,\n\\qquad\ns=\\frac{\\max_i |x_i|}{q_{\\max}},\n\\qquad\nQ_s(x_i)=s\\,\n\\operatorname{clip}\\!\\left(\n\\operatorname{round}\\!\\left(\\frac{x_i}{s}\\right),\n-q_{\\max},q_{\\max}\n\\right).\n$$ {#eq-c03-symmetric-quantizer}\n\nOne scale for $[0.1,0.2,0.3,100]$ must cover the outlier. The following model\nuses eight signed bits. It is a uniform integer quantizer, not a floating-point\nformat.\n\n:::: {.plan-code}\n::: {.plan}\n1. Quantize all four coordinates with one declared symmetric scale.\n2. Quantize the first three coordinates as one block and the outlier as another.\n3. Compare integer codes and reconstructed values.\n4. Assert that only the global scale erases every small coordinate.\n:::\n\n::: {#c03-grid-allocation .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: show an outlier collapsing a global quantization grid\"}\nvalues = np.array([0.1, 0.2, 0.3, 100.0])\n\n# [1]\nglobal_grid = symmetric_quantize(values, bits=8)\n\n# [2]\nblocked_grid = symmetric_quantize(values, bits=8, block_size=3)\n\n# [3]\nfor name, result in ((\"global\", global_grid), (\"blocked\", blocked_grid)):\n    print(\n        f\"{name:>7}: scales={np.array2string(result.scales, precision=6)}, \"\n        f\"codes={result.integer_codes.tolist()}\"\n    )\n    print(\n        \" \" * 9\n        + f\"reconstructed={np.array2string(result.dequantized, precision=6)}\"\n    )\n\n# [4]\nassert np.all(global_grid.integer_codes[:3] == 0)\nassert np.all(blocked_grid.integer_codes[:3] != 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n global: scales=[0.787402], codes=[0, 0, 0, 127]\n         reconstructed=[  0.   0.   0. 100.]\nblocked: scales=[0.002362 0.787402], codes=[42, 85, 127, 127]\n         reconstructed=[9.921260e-02 2.007874e-01 3.000000e-01 1.000000e+02]\n```\n:::\n:::\n\n\n::::\n\nThe global step is\n0\\.787402; every small coordinate lies below\nhalf that step and rounds to zero. The first block's step is\n0\\.002362, so those coordinates receive useful\ncodes. Nothing about the bit count alone predicted the difference. Scale\ngranularity was part of the algorithm.\n\nBlocking is not free. It stores more scales, adds grouping rules, and can\nintroduce discontinuities at block boundaries. The supported conclusion is\nnot that smaller blocks are always better. It is that a claim about\nquantization error is incomplete until scale selection and block axes are\nspecified.\n\n## Changing the rounding rule {#sec-c03-stochastic}\n\nThe opening update is always pushed toward the old state by deterministic\nrounding. A different rounding rule can remove that one-sided local error.\n\nLet $a<x<b$ be adjacent grid points. Define stochastic adjacent rounding by\n\n$$\n\\Pr(Q_{\\mathrm{sr}}(x)=a)=\\frac{b-x}{b-a},\n\\qquad\n\\Pr(Q_{\\mathrm{sr}}(x)=b)=\\frac{x-a}{b-a}.\n$$ {#eq-c03-stochastic-rule}\n\n::: {#thm-c03-stochastic-rounding phenomenon_id=\"c03-vanishing-update\"}\n## Unbiased adjacent stochastic rounding\n\nUnder @eq-c03-stochastic-rule,\n\n$$\n\\E[Q_{\\mathrm{sr}}(x)]=x,\n\\qquad\n\\E[(Q_{\\mathrm{sr}}(x)-x)^2]=(x-a)(b-x).\n$$ {#eq-c03-stochastic-moments}\n:::\n\n### Proof\n\nThe expectation is\n\n$$\na\\frac{b-x}{b-a}+b\\frac{x-a}{b-a}=x.\n$$\n\nThe error equals $-(x-a)$ when rounding to $a$ and $b-x$ when rounding\nto $b$. Its second moment is\n\n$$\n(x-a)^2\\frac{b-x}{b-a}\n+\n(b-x)^2\\frac{x-a}{b-a}\n=(x-a)(b-x).\n$$\n\nBecause the mean error is zero, this second moment is also the variance.\n$\\square$\n\nAt the opening state, each requested value is an integer plus $0.25$ and\nthe grid spacing remains one. Each step therefore moves upward with\nprobability $0.25$. Under independent draws, the endpoint has the model\n\n$$\n1024+\\operatorname{Binomial}(400,0.25),\n$$\n\nwith mean $1124$ and standard deviation\n$\\sqrt{400(0.25)(0.75)}\\approx 8.66$.\n\n:::: {.plan-code}\n::: {.plan}\n1. Run seeded stochastic-rounding trials under the opening contract.\n2. Estimate the endpoint mean, standard deviation, and standard error.\n3. Compare the mean with the exact endpoint and the binomial model.\n4. Plot the endpoint distribution with both reference locations.\n:::\n\n::: {.cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: replace deterministic stagnation with an unbiased endpoint estimator\"}\n# [1]\nstochastic_seed, trials = 6212, 20_000\nendpoints = stochastic_update_trials(\n    initial,\n    increment,\n    steps,\n    trials,\n    dtype=np.float16,\n    seed=stochastic_seed,\n).astype(np.float64)\n\n# [2]\nendpoint_mean = float(endpoints.mean())\nendpoint_sd = float(endpoints.std(ddof=1))\nendpoint_se = endpoint_sd / np.sqrt(trials)\n\n# [3]\nmodel_sd = np.sqrt(steps * 0.25 * 0.75)\nassert abs(endpoint_mean - trace.exact_final) < 4 * endpoint_se\nassert abs(endpoint_sd - model_sd) < 0.2\n\n# [4]\nfig, ax = plt.subplots(figsize=(7.0, 3.8))\nax.hist(endpoints, bins=np.arange(endpoints.min() - 0.5, endpoints.max() + 1.5),\n        color=\"#5379AA\", alpha=0.82)\nax.axvline(trace.exact_final, color=\"#2E7D32\", linewidth=2.2,\n           label=\"Exact endpoint\")\nax.axvline(trace.final, color=\"#9C2F2F\", linewidth=2.2, linestyle=\"--\",\n           label=\"Deterministic endpoint\")\nax.set(xlabel=\"stored endpoint\", ylabel=\"trial count\")\nax.legend(frameon=False)\nplt.show()\n\nprint(\n    f\"mean={endpoint_mean:.5f}, sd={endpoint_sd:.5f}, \"\n    f\"SE(mean)={endpoint_se:.5f}\"\n)\nprint(\n    f\"normal 95% interval for mean=\"\n    f\"[{endpoint_mean - 1.96 * endpoint_se:.5f}, \"\n    f\"{endpoint_mean + 1.96 * endpoint_se:.5f}]\"\n)\n```\n\n::: {.cell-output .cell-output-display}\n![Across 20,000 seeded trials, stochastic adjacent rounding centers the endpoint distribution near the exact endpoint 1124, whereas deterministic rounding ends at 1024. The figure supports an expectation claim for this declared model, not exact trajectories or general training convergence.](03-precision-contract_files/figure-pdf/fig-c03-stochastic-endpoints-output-1.pdf){#fig-c03-stochastic-endpoints fig-alt='Histogram of stochastic endpoints centered near 1124. A solid vertical line marks the exact endpoint at 1124 and a dashed line marks the deterministic endpoint at 1024, far to the left.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nmean=1124.00655, sd=8.64855, SE(mean)=0.06115\nnormal 95% interval for mean=[1123.88669, 1124.12641]\n```\n:::\n:::\n\n\n::::\n\nThe estimated mean is\n1124\\.00655, with standard error\n0\\.06115. The exact endpoint lies inside the displayed\nnormal-approximation interval for the mean. Individual trajectories remain\nnoisy; their standard deviation is about\n8\\.65.\n\n::: {.callout-warning title=\"Named wrong answer: 'Unbiased rounding makes the training run unbiased'\"}\nThe theorem concerns one rounding event conditional on its input. A later\nstate depends on earlier random outcomes, and nonlinear maps do not generally\npreserve unbiasedness. Stochastic rounding prevents this deterministic\nsub-grid stagnation in expectation. It does not prevent overflow, choose a\ngood scale, stabilize an update rule, or guarantee convergence.\n:::\n\n## Diagnose before prescribing {#sec-c03-audit}\n\nThe same symptom—no visible progress—admits different repairs.\n\n| Diagnostic | Instrument | Matched repair | Repair cannot do |\n|---|---|---|---|\n| Value exceeds range | Peak and exceptional-value trace | Rescale, widen exponent range, or change the evaluation | Recover an overflowed intermediate after the fact |\n| Update lies below local midpoint | $\\operatorname{ulp}(w)$ versus $|\\Delta w|$ | Retain a wider state, rescale, accumulate increments, or use a scoped rounding change | Make the mathematical update direction correct |\n| Inputs already coincide on the grid | Same-input wider reference | Change upstream storage or scaling | Infer distinctions absent from the input |\n| Nearby large operands expose prior errors | Cancellation ratio and wider controls | Reformulate or form operands more accurately | Repair arbitrary ill-conditioning |\n| One outlier sets a global quantization step | Per-block maxima and zero-code rate | Allocate scales by a declared block or channel | Eliminate scale metadata and boundary costs |\n| Long reduction loses increments | Accumulator dtype and reduction-order audit | Widen or compensate the accumulation | Establish accelerator speed from CPU timing |\n\nThis table is the precision language promised by Chapter 2. The dtype is one\nfield inside the diagnosis, not the diagnosis itself.\n\nThe same discipline will return in later acts. A variance-preserving\ninitialization must keep values in range as well as control exact moments.\nBatch-coordinate normalization inherits the centered-state estimator and its\naccumulator contract. An edge-of-stability trace needs a precision control\nbefore a spike is assigned to curvature. A quantized update must declare\nwhere its scale came from.\n\n::: {.callout-tip title=\"Check yourself\"}\nA stored parameter is $2048$ in FP16 and a computation requests\n$+0.75$. Without running code, compute the local spacing, identify the two\nadjacent stored candidates, and predict the round-to-nearest result. Which\npart of the answer would change under stochastic adjacent rounding?\n:::\n\n## Okay, so —\n\n- **Inherited:** Chapter 2 showed that algebraically equal formulas can have\n  different execution behavior and that wider downstream arithmetic cannot\n  reconstruct absent inputs.\n- **Changed:** “FP16” is no longer an explanation. The operative object is a\n  contract over storage, compute, accumulation, output, rounding, range, and\n  scale.\n- **Instrumented:** The harness now measures local spacing, queries format\n  envelopes, simulates round-after-each-step trajectories, audits block\n  quantizers, and estimates stochastic endpoints with uncertainty.\n- **Established:** Binade spacing predicts the stalled update; cancellation\n  amplifies operand errors relative to a small difference; stochastic\n  adjacent rounding is locally unbiased with an exact error variance.\n- **Unresolved:** Local unbiasedness is not trajectory-level convergence, CPU\n  simulation is not accelerator performance, and later chapters must test\n  whether an observed training failure is numerical, dynamic, or geometric.\n\n## Sources and further reading\n\nIEEE 754 specifies floating-point formats and operations\n[@ieee7542019]. Higham develops the standard rounding model, cancellation,\nstability, and error analysis in detail [@higham2002]. Connolly, Higham, and\nMary analyze stochastic rounding and its probabilistic backward-error\nbehavior [@connolly2021]. The FP8 proposal by Micikevicius and collaborators\nis useful modern format context, but it does not make a format name a complete\nexecution contract [@micikevicius2022].\n\nThe Probabilistic Numerics tutorial contrasts uncertainty from limited\ncomputation with uncertainty from limited data [@hennig2026tutorial].\nExercise 7 uses that analogy as an audit boundary: neither a deterministic\nrounding bound nor local unbiasedness is automatically a calibrated posterior\nover an unfinished computation.\n\nFor introductory format anatomy, mixed-precision roles, and the hardware\nmotivation, see the sibling volume's\n[precision and hardware appendix](https://shakeri-lab.github.io/dl-book/chapters/appendices/a3-precision-performance.html#sec-a3-precision-performance).\nThis chapter owns the local-grid diagnosis, the cancellation boundary,\nresolution allocation, and the rounding-rule audit.\n\n## Exercises\n\n1. **(Pencil.) Binade boundaries.** For FP16, compute the spacing immediately\n   below $2^{10}$, at $2^{10}$, and at $2^{11}$. Explain why\n   $\\operatorname{ulp}(x)$ jumps at a power of two even though relative\n   precision remains of the same order.\n\n2. **(Pencil.) Cancellation control.** Let $x=1+\\eta$ and $y=1$, with\n   $\\eta>0$. Use @eq-c03-cancellation-bound to identify the amplification\n   factor. Then explain why the bound diagnoses sensitivity without predicting\n   the exact sign of the error.\n\n3. **(Code.) Stagnation map.** Sweep represented FP16 states across several\n   binades and requested positive updates. Predict stagnation from the local\n   midpoint before running the harness. Report a confusion matrix between the\n   prediction and observed state changes.\n\n4. **(Code.) Scale allocation.** Add one adjustable outlier to a vector of\n   small coordinates. Compare global, fixed-block, and per-coordinate\n   symmetric scales using reconstruction error and zero-code rate. Count scale\n   metadata explicitly; do not rank methods on error alone.\n\n5. **(Audit.) The incomplete precision claim.** A report says, “The model was\n   trained in FP16 and remained stable.” Write the missing storage, compute,\n   accumulation, output, rounding, exceptional-value, and scaling questions.\n   For each question, name one rival explanation it could eliminate.\n\n6. **(Audit.) Paper audit: FP8 formats.** Complete the **Claim**,\n   **Mathematical object**, **Evidence culture and interface**, **Numerical and\n   hardware contract**, and **Transfer verdict** fields for the primary FP8\n   format proposal cited above. Extract one claim about a format, one about an execution path,\n   and one empirical result. For each, record its assumptions and identify\n   whether the paper's evidence is a proof, model calculation, simulation, or\n   hardware measurement. Do not convert a paper-reported endpoint into a\n   reproduced book claim.\n\n7. **(Audit.) Computational uncertainty.** Compare three objects: a\n   deterministic roundoff bound, stochastic adjacent rounding under the model\n   in this chapter, and a probabilistic numerical posterior\n   [@hennig2026tutorial]. For each, record the source of randomness, what is\n   conditioned on, what event the uncertainty statement covers, and what\n   calibration evidence would be needed. Explain why local unbiasedness of a\n   rounding error does not by itself quantify uncertainty in the exact\n   computation.\n\n",
    "supporting": [
      "03-precision-contract_files/figure-pdf"
    ],
    "filters": []
  }
}