{
  "hash": "afe1ac17a5aca287f26ac01f64f65aee",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nsubtitle: \"Empirical spectra, asymptotic laws, and finite nulls\"\ndescription: \"Why a Marchenko--Pastur edge is a model baseline rather than a finite-sample verdict.\"\nnumber-offset: 8\njupyter: python3\nharness-ref: ch-09\nharness-api: \"0.9\"\nharness-wheel-sha256: \"0d4b6e953774005f928e74b4e0617e4451f0e82c64adc4d7a1b4c4ad4a504751\"\nphenomenon_id: c09-bulk-not-verdict\nclaim_ids:\n  - c09-bulk-shape-001\n  - c09-finite-null-001\n  - c09-spike-threshold-001\nthreads:\n  random-matrix-spectra: callback\n  subgaussian-safe-zone: callback\nlenses:\n  geometric: primary\n  dynamic: quiet\n  algorithmic: supporting\nfulfills:\n  - promise-c08-c09-spectral-mass\n---\n\n# The Bulk Is Not a Verdict {#c09}\n\n<span class=\"thread\">RS · Random-matrix spectra</span>\n<span class=\"thread\">SG · The sub-Gaussian safe zone</span>\n<span class=\"lens-ledger\">Geometric primary · Dynamic quiet · Algorithmic supporting</span>\n\nGenerate $128$ observations with $64$ independent standard-normal\ncoordinates. The population covariance is exactly\n$\\matr{I}_{64}$. For the seeded realization below, the largest eigenvalue of\nthe sample covariance is\n\n$$ \n\\lambda_{\\max}(\\widehat{\\matr{\\Sigma}})\\approx 2.921.\n$$\n\nThe Marchenko--Pastur upper edge at aspect ratio\n$\\gamma=64/128=1/2$ is\n\n$$\n\\lambda_+=(1+\\sqrt{\\gamma})^2\\approx2.914.\n$$\n\nThe sample crosses the edge even though there is no population signal to\nfind.\n\n::: {.callout-important title=\"Prediction\"}\nDoes $\\lambda_{\\max}>\\lambda_+$ reject the pure-noise model? If not, what\nmust be calibrated before the word “signal” is justified?\n:::\n\n## The outlier is made of noise {#sec-c09-opening}\n\nThe matrix convention matters. Let\n$\\matr{X}\\in\\mathbb{R}^{m\\times n}$ have observations in rows and\ncoordinates in columns. Here the population mean is known to be zero, so the\nestimator is the sample second moment\n\n$$\n\\widehat{\\matr{\\Sigma}}\n=\n\\frac{1}{m}\\matr{X}^{\\mathsf T}\\matr{X}.\n$$ {#eq-c09-second-moment}\n\nIts eigenvalues are the squared singular values of\n$\\matr{X}/\\sqrt m$. C08 located those edges; this chapter instruments the\nmass between them. To prevent a hidden seed search, the witness seed is the\nfirst 32 bits of the SHA-256 digest of the registered phenomenon ID\n`c09-bulk-not-verdict`.\n\n:::: {.plan-code}\n::: {.plan}\n1. Verify and activate `harness@ch-09`.\n2. Generate the predeclared pure-noise witness.\n3. Form the known-zero-mean second-moment estimator and compute its exact eigenvalues.\n4. Evaluate the Marchenko--Pastur density under the matching aspect ratio.\n5. Plot the finite empirical spectrum and mark the limiting support edges.\n:::\n\n::: {.cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: construct a pure-noise edge crossing and overlay its asymptotic bulk\"}\nfrom hashlib import sha256\nimport json\nfrom pathlib import Path\nimport sys\n\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# [1]\nmanifest_path = Path(\"artifacts/harness/ch-09/manifest.json\")\nmanifest = json.loads(manifest_path.read_text())\nwheel_path = manifest_path.parent / manifest[\"wheel\"]\nassert sha256(wheel_path.read_bytes()).hexdigest() == manifest[\"wheel_sha256\"]\nsys.path.insert(0, str(wheel_path.resolve()))\n\nfrom trainable_harness import (\n    covariance_eigenvalues,\n    empirical_upper_threshold,\n    gaussian_covariance_trials,\n    marchenko_pastur_density,\n    marchenko_pastur_support,\n)\n\n# [2]\nsample_count, feature_count = 128, 64\nwitness_seed = int(\n    sha256(b\"c09-bulk-not-verdict\").hexdigest()[:8],\n    16,\n)\nrng = np.random.default_rng(witness_seed)\ndata = rng.standard_normal((sample_count, feature_count))\n\n# [3]\neigenvalues = covariance_eigenvalues(data)\naspect_ratio = feature_count / sample_count\nsupport = marchenko_pastur_support(aspect_ratio)\nassert eigenvalues[-1] > support.lambda_plus\n\n# [4]\ngrid = np.linspace(support.lambda_minus, support.lambda_plus, 700)\ndensity = marchenko_pastur_density(grid, aspect_ratio)\n\n# [5]\nfig, axis = plt.subplots(figsize=(7.2, 3.8))\naxis.hist(\n    eigenvalues,\n    bins=np.linspace(0.0, 3.12, 17),\n    density=True,\n    alpha=0.55,\n    color=\"#4c78a8\",\n    label=\"finite ESD histogram\",\n)\naxis.plot(grid, density, color=\"#1f4e79\", linewidth=2.2, label=\"MP density\")\naxis.axvline(\n    support.lambda_minus,\n    color=\"#6b6b6b\",\n    linestyle=\"--\",\n    label=r\"limiting edges $\\lambda_\\pm$\",\n)\naxis.axvline(support.lambda_plus, color=\"#6b6b6b\", linestyle=\"--\")\naxis.axvline(\n    eigenvalues[-1],\n    color=\"#e45756\",\n    linewidth=2.0,\n    label=\"pure-noise top eigenvalue\",\n)\naxis.set(xlabel=r\"eigenvalue $\\lambda$\", ylabel=\"spectral density\")\naxis.grid(alpha=0.22)\naxis.legend(frameon=False, fontsize=8)\nplt.tight_layout()\nplt.show()\n\nprint(f\"harness={manifest['harness_ref']} wheel={manifest['wheel_sha256'][:12]}\")\nprint(\n    f\"mean eigenvalue={np.mean(eigenvalues):.6f}; \"\n    f\"lambda_max={eigenvalues[-1]:.6f}\"\n)\nprint(\n    f\"MP edges=[{support.lambda_minus:.6f}, \"\n    f\"{support.lambda_plus:.6f}]\"\n)\n```\n\n::: {.cell-output .cell-output-display}\n![A pure-noise finite spectrum can cross an asymptotic edge. The histogram is the exact eigenvalue spectrum of one seeded 64-coordinate sample covariance from 128 independent standard-normal observations. The curve is the Marchenko--Pastur limiting density for the matching aspect ratio. The top eigenvalue lies beyond the limiting upper edge; that crossing is the symptom, not yet a rejection rule.](09-marchenko-pastur_files/figure-pdf/fig-c09-bulk-witness-output-1.pdf){#fig-c09-bulk-witness fig-alt='Histogram of 64 sample-covariance eigenvalues overlaid by a smooth Marchenko--Pastur density. Most eigenvalues fill the predicted bulk between about 0.086 and 2.914, while one pure-noise eigenvalue at about 2.921 sits just beyond the upper edge.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nharness=ch-09 wheel=0d4b6e953774\nmean eigenvalue=1.021187; lambda_max=2.921244\nMP edges=[0.085786, 2.914214]\n```\n:::\n:::\n\n\n::::\n\nThe overlay is visually persuasive and logically insufficient. The\nMarchenko--Pastur curve is a limit under a declared generative model. The\nhistogram is one finite random measure. Neither object says how often the\nlargest finite eigenvalue crosses the limiting support.\n\n## Name the estimator before naming the law {#sec-c09-estimator}\n\nThree similar-looking matrices answer different questions:\n\n| Mean contract | Computation | Denominator meaning |\n|---|---|---|\n| population mean known to be zero | $\\frac1m\\sum_i\\vect{x}_i\\vect{x}_i^{\\mathsf T}$ | unbiased second moment under the declared mean |\n| population mean unknown; maximum-likelihood Gaussian convention | $\\frac1m\\sum_i(\\vect{x}_i-\\bar{\\vect{x}})(\\vect{x}_i-\\bar{\\vect{x}})^{\\mathsf T}$ | centered average |\n| population mean unknown; unbiased covariance convention | $\\frac1{m-1}\\sum_i(\\vect{x}_i-\\bar{\\vect{x}})(\\vect{x}_i-\\bar{\\vect{x}})^{\\mathsf T}$ | degrees-of-freedom correction |\n\nChanging centering or denominator changes the finite null. The opening uses\nthe first row of the table. A report that says only “we computed the\ncovariance” has not specified its estimator.\n\nFor a symmetric matrix $\\matr{M}$ with eigenvalues\n$\\lambda_1,\\ldots,\\lambda_n$, define its **empirical spectral\ndistribution**\n\n$$\n\\mu_{\\matr{M}}\n=\n\\frac1n\\sum_{j=1}^n\\delta_{\\lambda_j}.\n$$ {#eq-c09-esd}\n\nThis is not merely a histogram. It is the exact probability measure that\nplaces mass $1/n$ at each finite eigenvalue. A histogram adds a binning\nchoice for visualization.\n\n::: {#thm-c09-esd-moments phenomenon_id=\"c09-bulk-not-verdict\"}\n## Trace moments of an empirical spectrum\n\nFor every nonnegative integer $k$,\n\n$$\n\\int \\lambda^k\\,d\\mu_{\\matr{M}}(\\lambda)\n=\n\\frac1n\\operatorname{tr}(\\matr{M}^k).\n$$ {#eq-c09-trace-moments}\n:::\n\n### Proof\n\nWrite\n$\\matr{M}=\\matr{Q}\\operatorname{diag}(\\lambda_1,\\ldots,\\lambda_n)\n\\matr{Q}^{\\mathsf T}$. Then\n\n$$\n\\operatorname{tr}(\\matr{M}^k)\n=\n\\sum_{j=1}^n\\lambda_j^k.\n$$\n\nIntegrating against the point masses in @eq-c09-esd gives the same sum divided\nby $n$. For $k=0$, the identity says that the ESD has total mass one.\n$\\square$\n\nThe first moment is normalized trace. For the sample covariance,\n\n$$\n\\int\\lambda\\,d\\mu_{\\widehat{\\matr{\\Sigma}}}(\\lambda)\n=\n\\frac{1}{mn}\\norm{\\matr{X}}_{\\mathrm F}^2.\n$$\n\nThe largest eigenvalue is a different functional. A correct mean does not pin\nthe upper edge, just as C08's Frobenius average did not pin both singular\nedges.\n\n## The bulk law is asymptotic {#sec-c09-mp}\n\n::: {#thm-c09-marchenko-pastur phenomenon_id=\"c09-bulk-not-verdict\"}\n## Marchenko--Pastur law\n\nLet $\\matr{X}\\in\\mathbb{R}^{m\\times n}$ have independent entries with mean\nzero, variance one, and finite fourth moment. Suppose\n$m,n\\to\\infty$ with\n\n$$\n\\frac{n}{m}\\longrightarrow\\gamma\\in(0,\\infty).\n$$\n\nThen the ESD of\n$\\widehat{\\matr{\\Sigma}}=\\matr{X}^{\\mathsf T}\\matr{X}/m$\nconverges almost surely, weakly, to the Marchenko--Pastur measure. Its\ncontinuous density is\n\n$$\n\\rho_\\gamma(\\lambda)\n=\n\\frac{\n\\sqrt{(\\lambda_+-\\lambda)(\\lambda-\\lambda_-)}\n}{\n2\\pi\\gamma\\lambda\n}\n\\mathbf{1}_{[\\lambda_-,\\lambda_+]}(\\lambda),\n$$ {#eq-c09-mp-density}\n\nwhere\n\n$$\n\\lambda_\\pm=(1\\pm\\sqrt{\\gamma})^2.\n$$ {#eq-c09-mp-edges}\n\nWhen $\\gamma>1$, the measure also has a point mass\n$1-1/\\gamma$ at zero.\n:::\n\n### Proof with pointer\n\nOne proof studies normalized traces of powers; another studies the Stieltjes\ntransform\n\n$$\ns_n(z)\n=\n\\frac1n\\operatorname{tr}\n\\left(\n\\widehat{\\matr{\\Sigma}}-z\\matr{I}\n\\right)^{-1}.\n$$\n\nIndependence and proportional growth produce a deterministic fixed-point\nequation for the limiting transform, whose inversion yields\n@eq-c09-mp-density. Establishing almost-sure convergence and controlling the\nresolvent error is the technical work. We use the theorem diagnostically and\npoint to the original paper for the full argument [@marchenko1967].\n\nThe scaling is part of the theorem. The entries of $\\matr{X}$ have variance\none and the Gram matrix is divided by $m$. Equivalently,\n$\\matr{A}=\\matr{X}/\\sqrt m$ has entry variance $1/m$ and\n$\\widehat{\\matr{\\Sigma}}=\\matr{A}^{\\mathsf T}\\matr{A}$. Mixing variance\n$1/n$ with the edges in @eq-c09-mp-edges changes the mean spectral scale by\na factor of $m/n$.\n\nC08's scaled Gaussian singular edges were\n$1\\pm\\sqrt{\\gamma}$. The eigenvalue edges here are their squares. The\nMarchenko--Pastur law adds the missing mass between them.\n\n::: {.callout-warning title=\"Named wrong answer: 'Above the MP edge means signal'\"}\nThe support describes a limiting measure. It does not say that every\neigenvalue of every finite null matrix lies inside the support. An edge\ncrossing becomes evidence only after the finite statistic, calibration rule,\nfalse-positive budget, and alternative model are declared.\n:::\n\n## A deterministic bulk can still be a poor covariance estimate {#sec-c09-covariance}\n\nThe sample spectrum can converge to a beautiful deterministic shape while the\nsample covariance remains far from the population covariance in operator\nnorm. For the isotropic case,\n\n$$\n\\norm{\\widehat{\\matr{\\Sigma}}-\\matr{I}}_{\\mathrm{op}}\n=\n\\max\\left\\{\n\\lambda_{\\max}(\\widehat{\\matr{\\Sigma}})-1,\\,\n1-\\lambda_{\\min}(\\widehat{\\matr{\\Sigma}})\n\\right\\}.\n$$ {#eq-c09-isotropic-error}\n\nAt fixed positive $\\gamma$, the limiting edges do not collapse to one.\n\n::: {#thm-c09-covariance-error phenomenon_id=\"c09-bulk-not-verdict\"}\n## Sub-Gaussian covariance-estimation error\n\nLet $\\vect{X}\\in\\mathbb{R}^n$ be centered with covariance\n$\\matr{\\Sigma}$, and assume that for every $\\vect{x}$,\n\n$$\n\\norm{\\langle\\vect{X},\\vect{x}\\rangle}_{\\psi_2}\n\\le\nK\\norm{\\langle\\vect{X},\\vect{x}\\rangle}_{L^2}.\n$$\n\nFor $m$ independent copies and the estimator in @eq-c09-second-moment,\n\n$$\n\\E\\norm{\n\\widehat{\\matr{\\Sigma}}-\\matr{\\Sigma}\n}_{\\mathrm{op}}\n\\le\nCK^2\n\\left(\n\\sqrt{\\frac{n}{m}}+\\frac{n}{m}\n\\right)\n\\norm{\\matr{\\Sigma}}_{\\mathrm{op}}.\n$$ {#eq-c09-covariance-error}\n:::\n\n### Diagnostic proof sketch\n\nWhiten the data:\n$\\vect{Z}=\\matr{\\Sigma}^{-1/2}\\vect{X}$. The whitened rows are isotropic\nand sub-Gaussian, so C08 controls all singular values of their data matrix.\nSquaring those bounds controls\n$\\norm{m^{-1}\\matr{Z}^{\\mathsf T}\\matr{Z}-\\matr{I}}_{\\mathrm{op}}$.\nConjugating by $\\matr{\\Sigma}^{1/2}$ contributes\n$\\norm{\\matr{\\Sigma}}_{\\mathrm{op}}$. Vershynin gives the full expectation\nand high-probability bookkeeping [@vershynin2018].\n\nThe ambient-dimension rate says that $m$ must scale like\n$n/\\varepsilon^2$ for relative operator error $\\varepsilon$. C10 will\nreplace $n$ with an effective dimension when the population spectrum is\nconcentrated. That promise is now contractual, not rhetorical.\n\n## Calibrate the finite statistic {#sec-c09-finite-null}\n\nReturn to the opening shape. The finite null must match:\n\n- $m=128$, $n=64$;\n- independent standard-normal entries;\n- known population mean zero, with no sample centering;\n- denominator $m$;\n- statistic $\\lambda_{\\max}$;\n- false-positive rate $\\alpha=0.05$;\n- one predeclared look.\n\nThe next study uses $2{,}000$ independent null matrices with a seed\ndifferent from the opening witness. The 95th empirical percentile is a\ncalibrated threshold for this contract—not a universal constant.\n\n:::: {.plan-code}\n::: {.plan}\n1. Reuse the declared shape and analytic Marchenko--Pastur edge.\n2. Generate an independently seeded finite Gaussian null ensemble.\n3. Compute the largest eigenvalue for every exact covariance matrix.\n4. Predeclare the upper five-percent empirical threshold.\n5. Compare the opening witness with both the asymptotic edge and finite threshold.\n:::\n\n::: {.cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: calibrate the largest eigenvalue under a matched finite null\"}\n# [1]\nasymptotic_edge = support.lambda_plus\n\n# [2]\nnull_trials, null_seed = 2000, 6291\nnull = gaussian_covariance_trials(\n    sample_count,\n    feature_count,\n    trials=null_trials,\n    seed=null_seed,\n)\n\n# [3]\nnull_max = null[\"lambda_max\"]\ncrossing_rate = np.mean(null_max > asymptotic_edge)\n\n# [4]\nfalse_positive_rate = 0.05\nfinite_threshold = empirical_upper_threshold(\n    null_max,\n    false_positive_rate=false_positive_rate,\n)\n\n# [5]\nwitness_max = eigenvalues[-1]\nfig, axis = plt.subplots(figsize=(7.2, 3.7))\naxis.hist(\n    null_max,\n    bins=34,\n    density=True,\n    color=\"#72b7b2\",\n    alpha=0.7,\n    label=r\"finite null for $\\lambda_{\\max}$\",\n)\naxis.axvline(\n    asymptotic_edge,\n    color=\"#6b6b6b\",\n    linestyle=\"--\",\n    linewidth=2.0,\n    label=\"asymptotic upper edge\",\n)\naxis.axvline(\n    finite_threshold,\n    color=\"#1f4e79\",\n    linewidth=2.0,\n    label=\"finite 95th percentile\",\n)\naxis.axvline(\n    witness_max,\n    color=\"#e45756\",\n    linewidth=2.0,\n    label=\"opening witness\",\n)\naxis.set(xlabel=r\"largest eigenvalue $\\lambda_{\\max}$\", ylabel=\"density\")\naxis.grid(alpha=0.22)\naxis.legend(frameon=False, fontsize=8)\nplt.tight_layout()\nplt.show()\n\nprint(\n    f\"null edge-crossing rate={crossing_rate:.4f}; \"\n    f\"finite threshold={finite_threshold:.6f}\"\n)\nprint(\n    f\"witness={witness_max:.6f}; \"\n    f\"reject at alpha={false_positive_rate:.2f}: \"\n    f\"{witness_max > finite_threshold}\"\n)\n```\n\n::: {.cell-output .cell-output-display}\n![The limiting upper edge is not a finite five-percent threshold. In 2,000 independently seeded pure-noise covariance matrices of the opening shape, 13.85 percent of largest eigenvalues exceed the asymptotic edge. The opening witness crosses that edge but remains below the empirical 95th-percentile null threshold. The histogram is a distribution of one predeclared statistic, not an ESD.](09-marchenko-pastur_files/figure-pdf/fig-c09-finite-null-output-1.pdf){#fig-c09-finite-null fig-alt='Histogram of 2,000 largest eigenvalues under a matched Gaussian null. A dashed line at 2.914 marks the Marchenko--Pastur edge, a solid line at about 2.988 marks the empirical 95th percentile, and the opening witness at about 2.921 lies between them.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nnull edge-crossing rate=0.1385; finite threshold=2.987940\nwitness=2.921244; reject at alpha=0.05: False\n```\n:::\n:::\n\n\n::::\n\nThe result resolves the symptom. In this finite ensemble, $13.85\\%$ of pure\nnoise matrices cross the limiting edge. The opening value $2.921$ is above\nthe edge but below the finite 95th percentile $2.988$. Under this\npredeclared test, it is not rejected.\n\nThe threshold is only as portable as its null contract. Correlated rows,\nheavy-tailed coordinates, sample centering, a different aspect ratio, or a\nsearch across many layers all require recalibration.\n\n::: {#thm-c09-repeated-looks phenomenon_id=\"c09-bulk-not-verdict\"}\n## Repeated-look false alarms\n\nIf each of $K$ inspected spectra has a null event with probability at most\n$\\alpha$, then\n\n$$\n\\Pr\\{\\text{at least one false alarm}\\}\\le K\\alpha.\n$$\n\nIf the looks are independent and each event has probability exactly\n$\\alpha$, then the probability is\n\n$$\n1-(1-\\alpha)^K.\n$$ {#eq-c09-repeated-looks}\n:::\n\n### Proof\n\nThe first statement is the union bound. Under independence, no false alarm\noccurs with probability $(1-\\alpha)^K$; take the complement. $\\square$\n\nAt twenty independent looks, a nominal five-percent per-look rule has about a\n$64.2\\%$ chance of at least one false alarm. If the asymptotic edge were\nmistaken for the threshold, the measured $13.85\\%$ per-look crossing rate\nwould produce about a $94.9\\%$ chance of at least one crossing. Monitoring\ncreates a multiple-comparison problem even before training dynamics enter.\n\n::: {.callout-note title=\"Field note: nulls are executable specifications\"}\nStore the null generator beside the diagnostic. Record shape, orientation,\ncentering, denominator, marginal distribution, dependence assumptions,\nstatistic, seed, trial count, quantile method, false-positive level, and number\nof looks. “Compared with MP” is a picture caption; it is not a reproducible\ntest.\n:::\n\n## Signal needs an alternative model {#sec-c09-spike}\n\nA finite null tells us which values are unusual under noise. It does not say\nwhich structured mechanism produced an unusual value. The smallest useful\nalternative is a rank-one population spike:\n\n$$\n\\matr{\\Sigma}_\\beta\n=\n\\operatorname{diag}(\\beta,1,\\ldots,1),\n\\qquad \\beta>1.\n$$ {#eq-c09-spiked-model}\n\nEven this genuine population structure need not create a separated sample\neigenvalue.\n\n::: {#thm-c09-spike-separation phenomenon_id=\"c09-bulk-not-verdict\"}\n## Rank-one spiked-covariance separation\n\nUnder the model in @eq-c09-spiked-model, independent standardized entries\nwith finite fourth moment, and\n$n/m\\to\\gamma\\in(0,1)$, the largest sample eigenvalue converges almost\nsurely to\n\n$$\n\\lambda_{\\max}\n\\longrightarrow\n\\begin{cases}\n(1+\\sqrt{\\gamma})^2,\n& \\beta\\le1+\\sqrt{\\gamma},\\\\[4pt]\n\\displaystyle\n\\beta\\left(1+\\frac{\\gamma}{\\beta-1}\\right),\n& \\beta>1+\\sqrt{\\gamma}.\n\\end{cases}\n$$ {#eq-c09-spike-separation}\n:::\n\n### Proof with pointer\n\nBaik and Silverstein characterize the almost-sure limits of sample\neigenvalues for finite-rank perturbations of the identity covariance\n[@baik2006]. The displayed rank-one formula is their specialization. The\nimportant diagnostic fact is the phase boundary: below\n$1+\\sqrt{\\gamma}$, a real population spike is asymptotically absorbed at\nthe null edge.\n\nFor $\\gamma=1/2$, the population threshold is about $1.707$. The next\nfinite study compares $\\beta=1$, a subcritical spike $\\beta=1.5$, and a\nsupercritical spike $\\beta=2.5$, each over $2{,}000$ independently seeded\nmatrices. All three use the same five-percent finite null threshold from the\nprevious study.\n\n:::: {.plan-code}\n::: {.plan}\n1. Declare null, subcritical, and supercritical population eigenvalues.\n2. Generate independent finite ensembles under the rank-one Gaussian model.\n3. Compute the exact largest sample eigenvalue in every trial.\n4. Compare each ensemble with the previously calibrated finite null threshold.\n5. Plot finite distributions and rejection fractions beside the asymptotic separation boundary.\n:::\n\n::: {.cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: compare finite subcritical and supercritical covariance spikes\"}\n# [1]\nmodels = [\n    (\"null\", 1.0, null_seed),\n    (\"subcritical\", 1.5, 6292),\n    (\"supercritical\", 2.5, 6293),\n]\n\n# [2]\nensembles = [\n    null\n    if beta == 1.0\n    else gaussian_covariance_trials(\n        sample_count,\n        feature_count,\n        trials=null_trials,\n        seed=seed,\n        population_spike=beta,\n    )\n    for _, beta, seed in models\n]\n\n# [3]\nmaxima = [ensemble[\"lambda_max\"] for ensemble in ensembles]\n\n# [4]\nrejection_rates = np.array(\n    [np.mean(values > finite_threshold) for values in maxima]\n)\nseparation_threshold = 1.0 + np.sqrt(aspect_ratio)\n\n# [5]\nlabels = [f\"{label}\\n\" + rf\"$\\beta={beta:g}$\" for label, beta, _ in models]\nfig, axes = plt.subplots(1, 2, figsize=(8.0, 3.8))\naxes[0].boxplot(\n    maxima,\n    tick_labels=labels,\n    whis=(5, 95),\n    showfliers=False,\n    patch_artist=True,\n    boxprops={\"facecolor\": \"#a0cbe8\"},\n    medianprops={\"color\": \"#1f4e79\", \"linewidth\": 2.0},\n)\naxes[0].axhline(\n    finite_threshold,\n    color=\"#e45756\",\n    linestyle=\"--\",\n    label=\"finite null threshold\",\n)\naxes[0].set(ylabel=r\"largest sample eigenvalue $\\lambda_{\\max}$\")\naxes[0].grid(alpha=0.22, axis=\"y\")\naxes[0].legend(frameon=False, fontsize=8)\n\nbars = axes[1].bar(\n    labels,\n    rejection_rates,\n    color=[\"#72b7b2\", \"#f2cf5b\", \"#e45756\"],\n)\naxes[1].axhline(\n    false_positive_rate,\n    color=\"#1f4e79\",\n    linestyle=\":\",\n    label=\"declared null rate\",\n)\naxes[1].set(ylabel=\"fraction above finite threshold\", ylim=(0.0, 1.0))\naxes[1].bar_label(bars, fmt=\"%.3f\", padding=3)\naxes[1].grid(alpha=0.22, axis=\"y\")\naxes[1].legend(frameon=False, fontsize=8)\nplt.tight_layout()\nplt.show()\n\nprint(f\"population separation threshold={separation_threshold:.6f}\")\nfor (label, beta, _), rate in zip(models, rejection_rates, strict=True):\n    print(f\"{label}: beta={beta:.1f}; fraction above threshold={rate:.4f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![A population spike is not the same as a separated sample eigenvalue. At aspect ratio one half, the subcritical population spike beta equals 1.5 remains close to the null largest-eigenvalue distribution and crosses the finite five-percent threshold in only 10.9 percent of trials. The supercritical spike beta equals 2.5 separates and crosses in 91.65 percent. Boxes span the interquartile range; whiskers show the fifth and ninety-fifth percentiles.](09-marchenko-pastur_files/figure-pdf/fig-c09-spike-threshold-output-1.pdf){#fig-c09-spike-threshold fig-alt='Two-panel figure comparing null, subcritical, and supercritical rank-one covariance models. The left panel shows largest-eigenvalue box plots: null and beta 1.5 overlap strongly, while beta 2.5 shifts upward. The right panel shows threshold-crossing rates of 5, 10.9, and 91.65 percent.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\npopulation separation threshold=1.707107\nnull: beta=1.0; fraction above threshold=0.0500\nsubcritical: beta=1.5; fraction above threshold=0.1090\nsupercritical: beta=2.5; fraction above threshold=0.9165\n```\n:::\n:::\n\n\n::::\n\nThe subcritical model contains genuine population structure, yet most finite\nsample spectra do not separate from the null. Conversely, an arbitrary\noutlier in a learned matrix does not inherit this theorem unless the spiked\ncovariance model is defensible.\n\nThe diagnostic hierarchy is now explicit:\n\n| Object | Question answered | Invalid shortcut |\n|---|---|---|\n| ESD | Where did this finite matrix place spectral mass? | a histogram proves the null |\n| Marchenko--Pastur law | What bulk emerges under an iid proportional-growth null? | the limiting edge is a finite test |\n| finite null | Is the predeclared statistic unusual at this exact shape and estimator? | unusual identifies the mechanism |\n| spiked alternative | When does one declared population perturbation separate? | every learned outlier is a spike |\n\nA Hessian, a parameter update, and a sample covariance are all symmetric\nmatrices after suitable products, but symmetry does not give them the same\ngenerative law. C12 will build a curvature-specific null. C14 will ask how\none-layer spectra compose through depth.\n\n::: {.callout-tip title=\"Check yourself\"}\nTwo teams inspect the same $50$ independently initialized layers. Team A\nflags every eigenvalue above the asymptotic Marchenko--Pastur edge. Team B\ncalibrates the maximum across all $50$ layers under a matched joint null.\nWhich team controls the experiment-level false-positive probability? List the\nmetadata needed to reproduce Team B's threshold.\n:::\n\n## Okay, so —\n\n- **Inherited:** C08 supplied singular edges and the aspect-ratio geometry;\n  C05 supplied a sub-Gaussian null class, and C06 warned that covariance\n  entries are squared quantities.\n- **Changed:** two edges became a full empirical spectral measure, and the\n  asymptotic bulk became a baseline rather than a finite verdict.\n- **Instrumented:** the harness now declares covariance orientation,\n  centering, denominator, Marchenko--Pastur support and density, finite\n  extreme-eigenvalue trials, and an empirical upper threshold.\n- **Established:** Marchenko--Pastur explains the limiting null mass under its\n  assumptions; covariance estimation can still have order-one operator error;\n  repeated looks spend a false-positive budget; and a genuine subcritical\n  population spike can remain inside the sample bulk.\n- **Unresolved:** ambient dimension is too crude when spectral mass is\n  concentrated. C10 will turn trace divided by the upper edge into effective\n  rank and replace parameter counting with a geometric size.\n\n## Sources and further reading\n\nMarchenko and Pastur establish the limiting empirical spectral law\n[@marchenko1967]. Vershynin supplies the sub-Gaussian covariance-estimation\ntheorem and its whitening argument [@vershynin2018]. Baik and Silverstein\nderive the almost-sure sample-eigenvalue limits for spiked population models\n[@baik2006]. The instructor's canonical RMT material supplied the ESD-to-bulk\nsequence and covariance-estimation question. Its finite-significance\nshortcut—“above the edge means signal”—was rejected and replaced with the\nmatched-null contract demonstrated here.\n\n## Exercises\n\n1. **(Pencil.) Mass, mean, and edge.** Construct two probability measures on\n   four nonnegative points with the same first moment but different maxima.\n   Realize them as ESDs of diagonal matrices. Explain why normalized trace\n   cannot replace an upper-edge diagnostic.\n\n2. **(Pencil.) The zero atom.** Let $n>m$. Prove directly from rank that\n   $\\matr{X}^{\\mathsf T}\\matr{X}$ has at least $n-m$ zero eigenvalues.\n   Show that their ESD mass tends to $1-1/\\gamma$ when $n/m\\to\\gamma>1$.\n\n3. **(Code.) Estimator contract.** Under one fixed Gaussian data generator,\n   compare known-zero-mean division by $m$, sample centering with division\n   by $m$, and sample centering with division by $m-1$. Calibrate a\n   separate finite largest-eigenvalue threshold for each. Report seeds,\n   denominators, trial counts, and quantile method.\n\n4. **(Code.) Finite shape audit.** Hold $\\gamma=1/2$ approximately fixed\n   while increasing $m,n$. Measure the probability that\n   $\\lambda_{\\max}$ crosses the limiting edge and the distance between the\n   edge and the empirical 95th percentile. Do not infer a convergence rate\n   from a log--log line without a theorem.\n\n5. **(Audit.) Null misspecification.** Replace independent Gaussian rows with\n   temporally correlated rows, then with heavy-tailed coordinates. Keep the\n   old threshold long enough to measure its false-positive rate. Identify\n   which Marchenko--Pastur and covariance-estimation assumptions were broken.\n\n6. **(Audit.) Paper audit: a model-specific outlier.** Read Baik and\n   Silverstein [@baik2006]. Extract the population model, aspect-ratio limit,\n   moment assumptions, separation condition, almost-sure conclusion, and the\n   quantity that remains asymptotic. Then review a spectral-outlier claim in\n   a current machine-learning paper: state whether its matrix has the same\n   generative model and propose a matched finite null if it does not.\n\n",
    "supporting": [
      "09-marchenko-pastur_files/figure-pdf"
    ],
    "filters": []
  }
}