{
  "hash": "7874a68195f4094f65ef928549738ddf",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ndescription: \"Why isotropy can preserve an average while adaptive singular directions stretch and contract very differently.\"\nnumber-offset: 7\njupyter: python3\nharness-ref: ch-08\nharness-api: \"0.8\"\nharness-wheel-sha256: \"9ec8176699a4a5f297fdbade68dd42d94cd46ab0e1940d79f705fe84a0b65cf1\"\nphenomenon_id: c08-one-average-two-edges\nclaim_ids:\n  - c08-average-edges-001\n  - c08-aspect-ratio-001\n  - c08-power-iteration-001\nthreads:\n  random-matrix-spectra: seed\n  subgaussian-safe-zone: callback\nlenses:\n  geometric: primary\n  dynamic: quiet\n  algorithmic: supporting\nfulfills:\n  - promise-c07-c08-adaptive-directions\n---\n\n# One Average, Two Edges: Random Operators and Singular Values {#c08}\n\n\n<span class=\"thread\">RS · Random-matrix spectra</span>\n<span class=\"thread\">SG · The sub-Gaussian safe zone</span>\n<span class=\"lens-ledger\">Geometric primary · Dynamic quiet · Algorithmic supporting</span>\n\nDraw a $64\\times64$ matrix $\\matr{A}$ with independent\n$\\mathcal{N}(0,1/64)$ entries. Before seeing it, choose the first coordinate\nvector $\\vect{e}_1$. In the seeded realization below,\n\n$$\n\\norm{\\matr{A}\\vect{e}_1}_2\\approx0.984,\n\\qquad\n\\frac{\\norm{\\matr{A}}_{\\mathrm{F}}^2}{64}\\approx1.019.\n$$\n\nBoth checks say “near one.” The same matrix has largest singular value about\n$2.036$ and smallest singular value about $0.0204$. Its most contracted\ndirection loses nearly two orders of magnitude relative to its most stretched\ndirection.\n\n::: {.callout-important title=\"Prediction\"}\nFor every fixed unit vector $\\vect{x}$,\n$\\E\\norm{\\matr{A}\\vect{x}}_2^2=1$. Which word in that statement prevents it\nfrom proving that the realized matrix preserves every direction? What\ndiagnostic replaces the expectation when the direction is chosen after the\nmatrix is observed?\n:::\n\n## The direction can adapt to the matrix {#sec-c08-opening}\n\nThe top and bottom singular vectors are functions of the realized matrix.\nThey are not fixed anchors to which one may apply a single-direction\nconcentration statement. C07 built the missing route from fixed anchors to\nadaptive extrema; this chapter gives those extrema names and instruments.\n\n:::: {.plan-code}\n::: {.plan}\n1. Load the chapter-pinned operator instruments.\n2. Generate one scaled Gaussian matrix from a declared seed.\n3. Compare a predeclared direction and the Frobenius average with exact SVD edges.\n4. Verify the stretches of the top and bottom right singular vectors.\n5. Plot the average checks beside the adaptive edges.\n:::\n\n::: {.cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: compare fixed, average, and data-dependent directional stretches\"}\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# [1]\n\nfrom trainable_harness import (\n    gaussian_singular_value_trials,\n    matrix_spectrum_summary,\n    power_iteration_spectral_norm,\n)\n\n# [2]\ndimension, matrix_seed = 64, 6224\nrng = np.random.default_rng(matrix_seed)\nmatrix = rng.standard_normal((dimension, dimension)) / np.sqrt(dimension)\n\n# [3]\nsummary = matrix_spectrum_summary(matrix)\nfixed_direction = np.zeros(dimension)\nfixed_direction[0] = 1.0\nfixed_stretch = np.linalg.norm(matrix @ fixed_direction)\nroot_mean_squared_stretch = np.sqrt(summary.mean_squared_stretch)\n\n# [4]\n_, singular_values, right_vectors_t = np.linalg.svd(\n    matrix,\n    full_matrices=False,\n)\ntop_stretch = np.linalg.norm(matrix @ right_vectors_t[0])\nbottom_stretch = np.linalg.norm(matrix @ right_vectors_t[-1])\nassert np.isclose(top_stretch, summary.sigma_max)\nassert np.isclose(bottom_stretch, summary.sigma_min)\nassert np.allclose(singular_values, np.asarray(summary.singular_values))\n\n# [5]\nlabels = [\"fixed\", \"RMS\", r\"$\\sigma_{\\max}$\", r\"$\\sigma_{\\min}$\"]\nvalues = [\n    fixed_stretch,\n    root_mean_squared_stretch,\n    summary.sigma_max,\n    summary.sigma_min,\n]\nfig, axis = plt.subplots(figsize=(6.9, 3.7))\nbars = axis.bar(labels, values, color=[\"#232D4B\", \"#2E7D32\", \"#E57200\", \"#9C2F2F\"])\naxis.axhline(1.0, color=\"black\", linestyle=\":\", label=\"isotropic center\")\naxis.set(ylabel=\"directional stretch\", yscale=\"log\", ylim=(0.01, 3.0))\naxis.grid(alpha=0.25, axis=\"y\")\naxis.legend(frameon=False)\naxis.bar_label(bars, fmt=\"%.3f\", padding=3)\nplt.tight_layout()\nplt.show()\n\nprint(f\"harness={manifest['harness_ref']} wheel={manifest['wheel_sha256'][:12]}\")\nprint(\n    f\"fixed={fixed_stretch:.6f}; \"\n    f\"mean squared={summary.mean_squared_stretch:.6f}\"\n)\nprint(\n    f\"sigma_max={summary.sigma_max:.6f}; \"\n    f\"sigma_min={summary.sigma_min:.6f}; \"\n    f\"kappa={summary.condition_number:.3f}\"\n)\n```\n\n::: {.cell-output .cell-output-display}\n![One average conceals two adaptive edges. For the seeded square Gaussian matrix, the predeclared coordinate direction and root-mean-squared directional stretch sit near one. The top singular direction stretches by about two, while the bottom singular direction nearly collapses. Exact SVD is the control; this one matrix is a witness, not an asymptotic law.](08-random-operators_files/figure-pdf/fig-c08-average-edges-output-1.pdf){#fig-c08-average-edges fig-alt='Bar chart on a logarithmic vertical scale. Fixed-direction stretch and root-mean-squared stretch are near one, the largest singular value is about two, and the smallest singular value is near 0.02.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nharness=ch-08 wheel=9ec8176699a4\nfixed=0.984012; mean squared=1.019185\nsigma_max=2.036060; sigma_min=0.020407; kappa=99.773\n```\n:::\n:::\n\n\n::::\n\nThis phenomenon does not contradict isotropy. For a fixed unit vector,\n\n$$\n\\E\\norm{\\matr{A}\\vect{x}}_2^2\n=\n\\sum_{i=1}^{m}\n\\E\\langle\\vect{a}_i,\\vect{x}\\rangle^2\n=1\n$$ {#eq-c08-fixed-isotropy}\n\nunder the $1/\\sqrt m$ scaling. The quantifiers are:\n\n$$\n\\text{for each fixed }\\vect{x},\n\\quad\n\\E_{\\matr{A}}[\\cdots]=1.\n$$\n\nThey are not:\n\n$$\n\\text{for each realized }\\matr{A},\n\\quad\n\\text{for every }\\vect{x},\\ [\\cdots]=1.\n$$\n\nMoving “every direction” through the random draw is exactly the uniformization\nproblem.\n\n## Two edges define the stretch interval {#sec-c08-svd}\n\nFor $\\matr{A}\\in\\mathbb{R}^{m\\times n}$ with $m\\ge n$, write the singular\nvalue decomposition\n\n$$\n\\matr{A}\n=\n\\matr{U}\\matr{\\Sigma}\\matr{V}^{\\mathsf T},\n\\qquad\n\\sigma_1\\ge\\cdots\\ge\\sigma_n\\ge0.\n$$ {#eq-c08-svd}\n\nWe use\n\n$$\n\\sigma_{\\max}(\\matr{A})=\\sigma_1,\n\\qquad\n\\sigma_{\\min}(\\matr{A})=\\sigma_n,\n\\qquad\n\\norm{\\matr{A}}_{\\mathrm{op}}=\\sigma_{\\max}(\\matr{A}).\n$$\n\n::: {#thm-c08-svd-stretch phenomenon_id=\"c08-one-average-two-edges\"}\n## Singular-value stretch interval\n\nFor every $\\vect{x}\\in\\mathbb{R}^n$,\n\n$$\n\\sigma_{\\min}(\\matr{A})\\norm{\\vect{x}}_2\n\\le\n\\norm{\\matr{A}\\vect{x}}_2\n\\le\n\\sigma_{\\max}(\\matr{A})\\norm{\\vect{x}}_2.\n$$ {#eq-c08-stretch-interval}\n\nBoth inequalities are attained at the corresponding right singular vectors.\n:::\n\n### Proof\n\nPut $\\vect{z}=\\matr{V}^{\\mathsf T}\\vect{x}$. Orthogonality preserves the\nEuclidean norm, so $\\norm{\\vect{z}}_2=\\norm{\\vect{x}}_2$ and\n\n$$\n\\norm{\\matr{A}\\vect{x}}_2^2\n=\n\\norm{\\matr{\\Sigma}\\vect{z}}_2^2\n=\n\\sum_{j=1}^{n}\\sigma_j^2z_j^2.\n$$\n\nBounding every $\\sigma_j^2$ between $\\sigma_n^2$ and $\\sigma_1^2$ proves\n@eq-c08-stretch-interval. Choosing $\\vect{x}$ as the first or last column of\n$\\matr{V}$ gives equality. $\\square$\n\nThe Frobenius norm measures a different summary:\n\n$$\n\\norm{\\matr{A}}_{\\mathrm{F}}^2\n=\n\\sum_{j=1}^{n}\\sigma_j^2,\n\\qquad\n\\frac{\\norm{\\matr{A}}_{\\mathrm{F}}^2}{n}\n=\n\\text{mean squared singular value}.\n$$ {#eq-c08-frobenius-average}\n\nThe average can equal one while the interval is wide. An exact isometry has\nevery singular value equal to one. This is the first entry in the book's\northogonality/scale ledger.\n\n::: {.callout-warning title=\"Named wrong answer: 'Small singular value means underflow'\"}\nA singular value is a relative geometric scale. Underflow is an absolute\narithmetic event determined by input magnitude, subsequent operations, dtype,\nand storage/accumulation rules. A small lower edge predicts directional\nsuppression; it does not, by itself, say that any represented number becomes\nsubnormal or zero.\n:::\n\n## From fixed rows to all directions {#sec-c08-subgaussian-edges}\n\nLet the unscaled rows $\\vect{a}_i\\in\\mathbb{R}^n$ be independent, centered,\nisotropic, and sub-Gaussian. For each fixed unit vector $\\vect{x}$,\n$\\langle\\vect{a}_i,\\vect{x}\\rangle$ lies in C05's safe zone. The squared\nquantity\n\n$$\n\\norm{\\matr{A}\\vect{x}}_2^2\n=\n\\sum_{i=1}^{m}\n\\langle\\vect{a}_i,\\vect{x}\\rangle^2\n$$\n\nlies in C06's sub-exponential regime. Bernstein controls this sum at one fixed\ndirection. A C07 net and a deterministic quadratic-form interpolation then\nextend the result over the sphere.\n\n::: {#thm-c08-subgaussian-edges phenomenon_id=\"c08-one-average-two-edges\"}\n## Two-sided sub-Gaussian matrix bound\n\nLet $\\matr{A}$ have independent, centered, isotropic, sub-Gaussian rows, and\nlet\n\n$$\nK=\\max_i\\norm{\\vect{a}_i}_{\\psi_2}.\n$$\n\nThere is a universal constant $C>0$ such that, for every $t\\ge0$, with\nprobability at least $1-2e^{-t^2}$,\n\n$$\n\\sqrt m-CK^2(\\sqrt n+t)\n\\le\n\\sigma_{\\min}(\\matr{A})\n\\le\n\\sigma_{\\max}(\\matr{A})\n\\le\n\\sqrt m+CK^2(\\sqrt n+t).\n$$ {#eq-c08-subgaussian-edges}\n:::\n\n### Diagnostic proof sketch\n\nFor fixed $\\vect{x}$, isotropy centers\n$m^{-1}\\norm{\\matr{A}\\vect{x}}_2^2$ at one. C06 turns each centered square\ninto a sub-exponential variable, so Bernstein bounds its deviation. Choose a\nconstant-radius net with exponentially many anchors, and let the exponent pay\nthe log covering cost from C07. Apply the symmetric quadratic-form version of\nthe net interpolation to\n\n$$\n\\frac{1}{m}\\matr{A}^{\\mathsf T}\\matr{A}-\\matr{I}.\n$$\n\nThe resulting operator-norm control bounds every eigenvalue of the Gram\nmatrix, hence every squared singular value. Careful conversion from squared\nedges to singular edges gives @eq-c08-subgaussian-edges. Vershynin supplies\nthe constant bookkeeping [@vershynin2026].\n\nThis proof anatomy is more important diagnostically than the unnamed\nuniversal constant:\n\n| Ingredient | Contribution |\n|---|---|\n| isotropy | center at $\\sqrt m$ before scaling |\n| sub-Gaussian row projections | fixed-direction tail |\n| squaring plus Bernstein | concentration of directional energy |\n| sphere cover | $\\sqrt n$ uniformization cost |\n| interpolation | all directions between anchors |\n\nThe lower statement becomes informative only when its displayed lower bound\nis positive. For a nearly square matrix, the generic theorem may correctly\nrefuse to certify a margin.\n\n## Aspect ratio opens the lower edge {#sec-c08-aspect-ratio}\n\nGaussian matrices admit a sharper benchmark. The sharp constants require\nGaussian comparison, not merely the elementary net calculation.\n\n::: {#thm-c08-gaussian-edges phenomenon_id=\"c08-one-average-two-edges\"}\n## Gaussian singular-edge benchmark\n\nLet $\\matr{G}\\in\\mathbb{R}^{m\\times n}$, $m\\ge n$, have independent\nstandard-normal entries. Then\n\n$$\n\\E\\sigma_{\\max}(\\matr{G})\n\\le\n\\sqrt m+\\sqrt n,\n\\qquad\n\\E\\sigma_{\\min}(\\matr{G})\n\\ge\n\\sqrt m-\\sqrt n.\n$$ {#eq-c08-gaussian-expectation-edges}\n\nGaussian concentration gives sub-Gaussian upper and lower deviations around\nthese edge locations. After scaling\n$\\matr{A}=\\matr{G}/\\sqrt m$, the benchmark interval is\n\n$$\n1-\\sqrt{\\frac{n}{m}}\n\\quad\\text{to}\\quad\n1+\\sqrt{\\frac{n}{m}}.\n$$ {#eq-c08-scaled-gaussian-edges}\n:::\n\n### Proof with pointer\n\nThe upper expectation is a supremum of the Gaussian process\n$\\langle\\matr{G}\\vect{x},\\vect{y}\\rangle$ over two unit spheres. The lower\nedge is the corresponding min--max process. Gaussian comparison bounds them\nby sums and differences of Gaussian-vector norms; Gaussian concentration\nthen supplies deviations. This chapter uses the result as a diagnostic\nbenchmark. The comparison proof is given in Vershynin\n[@vershynin2026].\n\nFor $m=n$, the lower benchmark is zero. It does not say that every finite\nsquare Gaussian matrix is singular. It says that this theorem supplies no\ndimension-independent positive lower margin. The opening realization's\ncondition number near $99.8$ is therefore not evidence against isotropy.\n\nThe next study holds $n=64$ fixed and increases $m$. Every point is computed\nfrom exact SVDs of $160$ independently seeded finite matrices. The curves in\n@eq-c08-scaled-gaussian-edges are benchmarks, not fitted parameters and not\nan empirical spectral-density theorem.\n\n:::: {.plan-code}\n::: {.plan}\n1. Fix the input dimension and a grid of row counts.\n2. Generate independent scaled Gaussian matrices for each shape.\n3. Compute exact upper and lower singular edges for every trial.\n4. Report predeclared 5th, 50th, and 95th percentiles.\n5. Compare the finite ensembles with the aspect-ratio benchmark.\n:::\n\n::: {.cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: measure how aspect ratio separates the two singular edges\"}\n# [1]\ncolumns = 64\nrows_grid = np.array([64, 128, 256])\ntrials = 160\n\n# [2]\nensembles = [\n    gaussian_singular_value_trials(\n        int(rows),\n        columns,\n        trials=trials,\n        seed=6225 + index,\n    )\n    for index, rows in enumerate(rows_grid)\n]\n\n# [3]\nlower = np.array([np.median(item[\"sigma_min\"]) for item in ensembles])\nupper = np.array([np.median(item[\"sigma_max\"]) for item in ensembles])\nlower_interval = np.array(\n    [\n        [np.quantile(item[\"sigma_min\"], 0.05), np.quantile(item[\"sigma_min\"], 0.95)]\n        for item in ensembles\n    ]\n)\nupper_interval = np.array(\n    [\n        [np.quantile(item[\"sigma_max\"], 0.05), np.quantile(item[\"sigma_max\"], 0.95)]\n        for item in ensembles\n    ]\n)\n\n# [4]\nlower_error = np.vstack((lower - lower_interval[:, 0], lower_interval[:, 1] - lower))\nupper_error = np.vstack((upper - upper_interval[:, 0], upper_interval[:, 1] - upper))\n\n# [5]\nratios = rows_grid / columns\nbenchmark_lower = 1.0 - 1.0 / np.sqrt(ratios)\nbenchmark_upper = 1.0 + 1.0 / np.sqrt(ratios)\nfig, axis = plt.subplots(figsize=(7.2, 3.8))\naxis.errorbar(\n    ratios,\n    upper,\n    yerr=upper_error,\n    fmt=\"o-\",\n    capsize=4,\n    linewidth=2.0,\n    label=r\"exact $\\sigma_{\\max}$ quantiles\",\n)\naxis.errorbar(\n    ratios,\n    lower,\n    yerr=lower_error,\n    fmt=\"s-\",\n    capsize=4,\n    linewidth=2.0,\n    label=r\"exact $\\sigma_{\\min}$ quantiles\",\n)\naxis.plot(ratios, benchmark_upper, \"--\", color=\"gray\", label=\"Gaussian benchmark\")\naxis.plot(ratios, benchmark_lower, \"--\", color=\"gray\")\naxis.axhline(1.0, color=\"black\", linestyle=\":\")\naxis.set(\n    xlabel=r\"aspect ratio $m/n$\",\n    ylabel=\"scaled singular value\",\n    xticks=ratios,\n)\naxis.grid(alpha=0.25)\naxis.legend(frameon=False, ncol=2)\nplt.tight_layout()\nplt.show()\n\nfor rows, lo, hi in zip(rows_grid, lower, upper, strict=True):\n    print(\n        f\"shape={rows}x{columns}: \"\n        f\"median sigma_min={lo:.6f}, median sigma_max={hi:.6f}\"\n    )\n```\n\n::: {.cell-output .cell-output-display}\n![Aspect ratio changes the margin between singular edges. Exact SVD quantiles from 160 finite Gaussian matrices per shape move toward the scaled Gaussian benchmark as the row count grows relative to the fixed input width. The square case has no positive lower benchmark; taller maps open one. Error bars show empirical fifth-to-ninety-fifth percentile ranges, not confidence intervals for a population edge.](08-random-operators_files/figure-pdf/fig-c08-aspect-ratio-output-1.pdf){#fig-c08-aspect-ratio fig-alt='Plot of singular value versus row-to-column ratio one, two, and four. Median largest singular values decrease from about 1.94 to 1.47, while median smallest singular values increase from about 0.008 to 0.515. Error bars show fifth and ninety-fifth percentiles, and dashed benchmark curves follow one plus or minus the inverse square root of the row-to-column ratio.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nshape=64x64: median sigma_min=0.008079, median sigma_max=1.944530\nshape=128x64: median sigma_min=0.310570, median sigma_max=1.670645\nshape=256x64: median sigma_min=0.514655, median sigma_max=1.473261\n```\n:::\n:::\n\n\n::::\n\nThe median lower edge rises from about $0.0081$ in the square ensemble to\n$0.515$ at aspect ratio four. Meanwhile, the fixed-direction squared stretch\nand the mean squared singular value remain centered near one. “Preserves scale\non average” and “has a positive uniform margin” are different claims.\n\n## One-sided instruments answer one-sided questions {#sec-c08-power}\n\nExact SVD is appropriate for these laptop controls, but expensive for a large\nmatrix. **Power iteration** repeatedly applies\n$\\matr{A}^{\\mathsf T}\\matr{A}$:\n\n$$\n\\vect{v}_{k+1}\n=\n\\frac{\n\\matr{A}^{\\mathsf T}\\matr{A}\\vect{v}_k\n}{\n\\norm{\\matr{A}^{\\mathsf T}\\matr{A}\\vect{v}_k}_2\n}.\n$$ {#eq-c08-power-iteration}\n\nWhen the initialization has a component in the top right singular direction\nand the top eigenvalue is separated, the iteration amplifies that component.\nThe estimate $\\norm{\\matr{A}\\vect{v}_k}_2$ approaches\n$\\sigma_{\\max}(\\matr{A})$.\n\n:::: {.plan-code}\n::: {.plan}\n1. Reuse the seeded matrix with an exact SVD control.\n2. Initialize one unit vector from a separate declared seed.\n3. Apply power iteration to the Gram operator.\n4. Record the upper-edge estimate at every iteration.\n5. Plot relative error and state which edge the instrument never queried.\n:::\n\n::: {.cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: validate a one-sided spectral instrument against exact SVD\"}\n# [1]\nexact_upper = summary.sigma_max\nexact_lower = summary.sigma_min\n\n# [2]\niteration_seed, iterations = 6228, 25\n\n# [3]\ntrace = power_iteration_spectral_norm(\n    matrix,\n    iterations=iterations,\n    seed=iteration_seed,\n)\n\n# [4]\nestimates = np.asarray(trace.estimates)\nrelative_error = np.abs(estimates - exact_upper) / exact_upper\nassert relative_error[-1] < relative_error[0]\n\n# [5]\nfig, axis = plt.subplots(figsize=(6.9, 3.6))\naxis.semilogy(\n    np.arange(1, iterations + 1),\n    relative_error,\n    \"o-\",\n    markersize=3.5,\n    linewidth=2.0,\n)\naxis.set(\n    xlabel=\"power iteration\",\n    ylabel=r\"relative error in $\\sigma_{\\max}$\",\n)\naxis.grid(alpha=0.25, which=\"both\")\naxis.text(\n    0.98,\n    0.94,\n    rf\"$\\sigma_{{\\min}}={exact_lower:.4f}$ was not queried\",\n    transform=axis.transAxes,\n    ha=\"right\",\n    va=\"top\",\n)\nplt.tight_layout()\nplt.show()\n\nprint(\n    f\"first estimate={estimates[0]:.6f}; \"\n    f\"last estimate={estimates[-1]:.6f}; \"\n    f\"exact sigma_max={exact_upper:.6f}\"\n)\nprint(f\"exact sigma_min={exact_lower:.6f}; power-iteration estimate=not produced\")\n```\n\n::: {.cell-output .cell-output-display}\n![Power iteration is an upper-edge instrument. On the seeded control matrix, the estimate approaches the exact largest singular value over 25 iterations. The exact smallest singular value is shown only as a separate SVD control; it is not estimated by this trajectory. Convergence here validates the implementation on one matrix, not a universal iteration count.](08-random-operators_files/figure-pdf/fig-c08-power-iteration-output-1.pdf){#fig-c08-power-iteration fig-alt='Semilog plot of relative error in the largest singular value estimate over 25 power iterations. Error decreases from order one toward below one ten-thousandth. An annotation states that the smallest singular value, about 0.0204, was not queried.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nfirst estimate=0.960212; last estimate=2.035936; exact sigma_max=2.036060\nexact sigma_min=0.020407; power-iteration estimate=not produced\n```\n:::\n:::\n\n\n::::\n\nPower iteration controls the largest singular value only. Applying the same\nroutine longer does not turn it into a lower-edge diagnostic. The smallest\nedge requires a different method—often an inverse or shifted procedure—and\nthat procedure has its own conditioning and linear-solve contract.\n\n::: {.callout-note title=\"Field note: keep an exact small control\"}\nAt production scale, randomized or iterative estimators may be necessary.\nBefore trusting them, run the identical code path on matrices small enough for\nan exact SVD. Record the stopping rule, iteration count, initialization, and\nspectral-gap sensitivity. An approximate instrument without a control can\nconfuse estimator failure with a changing matrix.\n:::\n\nThe boundary between lenses is now explicit:\n\n| Observation | What it diagnoses | What remains missing |\n|---|---|---|\n| small $\\sigma_{\\min}$ | relative directional suppression | absolute activation/gradient scale and dtype |\n| large $\\sigma_{\\max}$ | relative directional amplification | nonlinearities and trajectory |\n| wide singular interval | poor realized isometry | whether products across depth worsen or cancel it |\n| power estimate | upper edge under an iteration contract | lower edge and full spectral mass |\n\nC03 decides when an absolute represented value is unsafe. C14 will decide how\nsingular intervals compose across depth. C09 asks the question omitted here:\nhow is the spectral mass distributed between the two edges?\n\n::: {.callout-tip title=\"Check yourself\"}\nA scaled random matrix satisfies\n$\\norm{\\matr{A}}_{\\mathrm{F}}^2/n=1$ exactly, and a power iteration estimates\n$\\sigma_{\\max}=1.8$. Can you bound $\\sigma_{\\min}$ away from zero from those\ntwo numbers alone? Construct a set of singular values with the same Frobenius\naverage and upper edge but an arbitrarily small lower edge.\n:::\n\n## Okay, so —\n\n- **Inherited:** C05 controlled fixed sub-Gaussian projections, C06 controlled\n  their squares, and C07 supplied the finite-cover route to adaptive extrema.\n- **Changed:** the diagnostic target is a realized random operator, so a fixed\n  expectation or Frobenius average no longer stands in for all directions.\n- **Instrumented:** the harness now reports exact singular summaries, seeded\n  aspect-ratio ensembles, and a power-iteration trace validated against exact\n  SVD.\n- **Established:** singular values bound every directional stretch; isotropy\n  sets a fixed-direction center; concentration plus covering creates a\n  dimension-dependent edge interval; aspect ratio controls whether the\n  Gaussian lower benchmark has positive margin.\n- **Unresolved:** What does the spectral mass between two random-matrix edges\n  say, and when does a finite outlier carry evidence rather than noise?\n\n## Sources and further reading\n\nVershynin develops the singular-value identities, two-sided sub-Gaussian\nmatrix theorem, and Gaussian comparison bounds used here\n[@vershynin2026]. Miyato, Kataoka, Koyama, and Yoshida use power\niteration inside an upper-edge intervention [@miyato2018]; the paper supplies\na useful audit of what such an instrument controls and what it leaves\nunmeasured.\n\nFor the general theory, use @vershynin2026; this chapter's contribution is\nthe matched two-edge witness and its finite certificate boundary.\n\n**Reading order.** Start with @vershynin2026 for the two-edge theorem and its\ncovering proof, then use @miyato2018 to audit what an upper-edge intervention\ndoes not say about the lower edge.\n\n## Exercises\n\n1. **(Pencil.) Same average, different interval.** Construct two diagonal\n   $4\\times4$ matrices with equal Frobenius norm and unequal operator norm.\n   Then make the second matrix's smallest singular value arbitrarily close to\n   zero while preserving its Frobenius norm.\n\n2. **(Pencil.) Shape is part of the theorem.** For a wide matrix\n   $\\matr{A}\\in\\mathbb{R}^{m\\times n}$ with $m<n$, prove that its action on the\n   full input space has lower edge zero. Explain why NumPy's list of\n   $\\min(m,n)$ returned singular values can obscure this nullspace if the shape\n   contract is omitted.\n\n3. **(Code.) Fixed versus adaptive directions.** Repeat the opening study for\n   dimensions $16$, $64$, and $256$. Predeclare ten unit directions before\n   each matrix draw. Compare their largest stretch with exact singular edges,\n   reporting seeds, trial denominators, and empirical quantiles.\n\n4. **(Code.) Instrument sensitivity.** Build diagonal matrices with controlled\n   ratios $\\sigma_2/\\sigma_1$. Measure the iterations required for power\n   iteration to reach a fixed relative error over many initializations.\n   Relate failures to the starting component in the top direction.\n\n5. **(Audit.) Geometry is not arithmetic.** A report observes\n   $\\sigma_{\\min}=10^{-4}$ and declares that gradients underflow in FP16.\n   List the missing absolute-scale, operation, storage, and accumulation facts.\n   Design the smallest dtype-aware experiment that could support the narrower\n   arithmetic claim.\n\n6. **(Audit.) Paper audit: an upper-edge intervention.** Complete the\n   **Mathematical object**, **Evidence culture and interface**, **Numerical and\n   hardware contract**, **Discriminating control**, and **Transfer verdict**\n   fields for Miyato, Kataoka, Koyama, and Yoshida [@miyato2018]. Extract the target singular\n   quantity, the power-iteration approximation, the persistence of its\n   auxiliary vectors, and the empirical stability endpoint. State precisely\n   what the method controls, then identify why that evidence does not imply a\n   positive lower singular edge or a bounded condition number.\n\n",
    "supporting": [
      "08-random-operators_files/figure-pdf"
    ],
    "filters": []
  }
}